[requirement]
====
[%metadata]
label:: /req/zone-query/zones-list-response
description:: For the response to a query requesting a list of DGGS zones:
part:: The response of the HTTP GET operation SHALL have a status code of 200.
part:: The content of the response SHALL be a list of zones fully covering where data is available
(in the case where the resource is associated with a particular dataset), and
matching any additional query parameters specified by the client (e.g., a filtering query parameter),
without any redundancy.
part:: Unless the zones is a compact list of zones (see `compact-zones` parameter), the zones returned
SHALL all be of the same DGGS hierarchy level.
part:: The selection of an encoding for the returned list of zones SHALL be consistent with
HTTP content negotiation.
part:: The implementation SHALL support at minimum a JSON encoding (media type `application/json`)
where each zone ID is specified as a string within an array of zones assigned to a `zones` property
within a JSON object (e..g, `{ "zones": [ "1-E-14", "1-E-15", "1-F-14", "1-F-15", "1-F-16" ] }`.
====
