[[req_data-retrieval_zone-depth-definition]]

[requirement]
====
[%metadata]
label:: /req/data-retrieval/rc-zone-depth-definition
description:: Parameter to specify the DGGS resolution levels to request data from beyond the requested zone's hierarchy level.
part:: The HTTP GET operation on a resource path
ending with `.../dggs/{dggsId}/zones/{zoneId}/data` SHALL support a parameter `zone-depth.

part:: The `zone-depth` parameter specifies the DGGS resolution levels beyond the requested zone's hierarchy level from which to retrieve data.
The zone-depth can be either:

* A single positive integer value - representing a specific `zone-level` to return (e.g. zone-depth=5);

* A range of positive integer values in the form "{low}-{high}" - representing a continuous range of `zone-levels` to return (e.g. zone-depth=1-8); or,

* A comma separated list of at least two (2) positive integer values - representing a set of specific `zone-levels` to return (e.g. zone-depth=1,3,7).  
part:: A `zone-depth` of 0 (e.g. zone-depth=0) corresponds to a single value, or a set of single values, (properties / field values) for the requested zone.

part:: The parameter `zone-depth` SHALL have the following characteristics (using an OpenAPI Specification 3.0 fragment):
[source,YAML]
----
name: zone-depth
in: query
description: |-
  This parameter specifies the DGGS resolution levels beyond to requested zone's hierarchy level from which to retrieve data.
  The zone-depth can be either:
  
  * A single positive integer value - representing a specific `zone-level` to return (e.g. zone-depth=5);
  
  * A range of positive integer values in the form "{low}-{high}" - representing a continuous range of `zone-levels` to return (e.g. zone-depth=1-8); or,
  
  * A comma separated list of at least two (2) positive integer values - representing a set of specific `zone-levels` to return (e.g. zone-depth=1,3,7).  
required: false
schema:
  oneOf:
  	- type: integer
  	  minimum: 0
  	- type: string
  	- type: array
  	  items:
  	    minItems: 2
  	    type: integer
  	    minimum: 0
  default: 0
style: form
----


NOTE: The `default` value in the schema can be set to any valid value and/or form defined above and in accordance with the DGGS data mapping approach deployed by the server.

====
