[[req_data-retrieval_zone-depth-response]]

[requirement]
====
[%metadata]
label:: /req/data-retrieval/rc-zone-depth-response
description:: Response requirements for the Parameter specifying the DGGS resolution levels to request data from beyond the requested zone's hierarchy level.
part:: If a `zone-depth` is specified, the operation SHALL return the data at the resolution / scale specified
by the `zone-depth` parameter, in accordance to the capabilities of the data packet encoding.
part:: The data encoding may support a fixed depth, a range of depths, and/or an arbitrary selection of depths.
part:: If the `zone-depth` parameter is omitted, the `default` value in the schema of `zone-depth` SHALL be assumed by the server, in accordance to the capabilities of the data packet encoding.


NOTE: A use case for a `zone-depth` of 0 would be to query the single set of values for a specific DGGS zone.

NOTE: For use cases such as visualization and performing analysis over a certain area,
a non-zero `zone-depth` would normally be used to avoid an overwhelming number of server round-trips.
In this case, more than a single value would be returned for each zone request,
with values returned for descendent zones at `zone-depth` levels deeper than the requested zone's level.
For example, requesting data for a level 10 zone with a `zone-depth` of 8 would return
individual values for each level 18 zones contained within that level 10 zone being requested.

====