= Standard template in Metanorma

== Content

This repository contains the content for an OGC standard.

* `document.adoc` - the main standard document with references to all sections
* remaining ``adoc``s - each section of the standard document is in a separate document: follow directions in each document to populate
* `figures` - figures go here
* `images` - Image files for graphics go here. Image files for figures go in the `figures` directory. Only place in here images not used in figures (e.g., as parts of tables, as logos, etc.)
* `requirements` - directory for requirements and requirement classes to be referenced in `clause_7_normative_text.adoc`
* `code` - sample code to accompany the standard, if desired
* `abstract_tests` - the Abstract Test Suite comprising one test for every requirement, optional
* `UML` - UML diagrams, if applicable

== Building

Run `make`.


== OGC Standard Document Template Initialisation (Linux)

Commands to initialise and compile the OGC Metanorma Standard document template. These should be run from the root directory of this github repository.

1. Download/update the Metanorma Docker Container

[NOTE]
====
docker pull metanorma/mn:latest
====

2. Create new Metanorma OGC standard from OGC Template

[NOTE]
====
Example:

docker run -i -v "$(pwd)":/metanorma metanorma/mn  metanorma new -d standard -t ogc  -l https://github.com/metanorma/mn-templates-ogc 21_038_OGC_API_DGGS_Part_1
====

3. Update Docker Instance with data from this github repository

[NOTE]
====
docker cp ./ <Docker_Container_ID>:"/metanorma/21_038_OGC_API_DGGS_Part_1"

Example:

docker cp ./ 2622352e28ed:"/metanorma/21_038_OGC_API_DGGS_Part_1"
====


4. Compile document

[NOTE]
====
Example:

docker run -v "$(pwd)":/metanorma -v ${HOME}/.fontist/fonts/:/config/fonts  metanorma/mn  metanorma compile --agree-to-terms -t ogc -x xml,html,doc 21_038_OGC_API_DGGS_Part_1/document.adoc

====

5. Copy the compiled Metanorma documents back to the github repository local directory.

[NOTE]
====
docker cp <Docker_Container_ID>:"/metanorma/21_038_OGC_API_DGGS_Part_1" .

Example:

docker cp 2622352e28ed:"/metanorma/21_038_OGC_API_DGGS_Part_1" .
====


6. Commit the changes and compiled Metanorma documents to github

[NOTE]
====
Example:

git commit -m "Changes to Conformance Class 1"

git push
====




