[appendix,obligation="normative"]

== Conformance Class Abstract Test Suite

=== Conformance Class "Core"

[[conf_core,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/core]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/core
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/core
classification:: Target Type:Web API
abstract-test:: /conf/core/dggrs-list
abstract-test:: /conf/core/dggrs-description
abstract-test:: /conf/core/zone-info
====

==== Abstract Test for Requirement Listing available DGGRS

[[conf_core_dggrs-list,/conf/core/dggrs-list]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/dggrs-list
target:: /req/core/dggrs-list
test-purpose:: Verify that the Implementation supports listing the available DGGRSs
test-method::
+
--
*Given:* a geospatial data resource conforming to the DGGS API Standard, with an API path including `.../dggs` or discovered following a link with relation type `[ogc-rel:dggrs-list]` +
*When:* performing a GET operation on the `.../dggs` resource with an `application/json` media type specified in the `Accept:` header (e.g., `Accept: application/json`) +
*Then:* (assert that all parts of the requirement are fully satisfied)
====

==== Abstract Test for Requirement Discrete global grid reference system description

[[conf_core_dggrs-description,/conf/core/dggrs-description]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/dggrs-description
target:: /req/core/dggrs-description
test-purpose:: Verify that the Implementation supports retrieving information for a particular DGGRS
test-method::
+
--
*Given:* a DGGRS resource identified from listing available DGGRS or discovered by following a link with relation type `[ogc-rel:dggrs]` +
*When:* performing a GET operation on the `.../dggs/{dggrsId}` resource with an `application/json` media type specified in the `Accept:` header (e.g., `Accept: application/json`) +
*Then:* (assert that all parts of the requirement are fully satisfied)
====

==== Abstract Test for Requirement Retrieving zone information

[[conf_core_zone-info,/conf/core/zone-info]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/zone-info
target:: /req/core/zone-info
test-purpose:: Verify that the Implementation supports retrieving information for a particular DGGRS zone
test-method::
+
--
*Given:* a DGGRS zone information resource identified from a `[ogc-rel:dggrs-zone-info]` link template within a DGGRS description resource, replacing the `{zoneId}` variable with a known valid identifier for the DGGRS, not beyond the `maxRefinementLevel` if one is specified +
*When:* performing a GET operation on the `.../dggs/{dggrsId}/zones/{zoneID}` resource with an `application/json` media type specified in the `Accept:` header (e.g., `Accept: application/json`) +
*Then:* (assert that all parts of the requirement are fully satisfied)
====

=== Conformance Class "Data Retrieval"

[[conf_data-retrieval,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-retrieval]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-retrieval
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-retrieval
classification:: Target Type:Web API
abstract-test:: /conf/data-retrieval/zone-data
====

==== Abstract Test for Requirement Retrieving data from a zone

[[conf_data-retrieval_zone-data,/conf/data-retrieval/zone-data]]
[abstract_test]
====
[%metadata]
identifier:: /conf/data-retrieval/zone-data
target:: /req/data-retrieval/zone-data
test-purpose:: Verify that the Implementation supports retrieving data for a particular DGGRS zone
test-method::
+
--
*Given:* a DGGRS zone data resource identified from a `[ogc-rel:dggrs-zone-data]` link template within a DGGRS description resource, replacing the `{zoneId}` variable with a known valid identifier for the DGGRS, not beyond the `maxRefinementLevel` if one is specified +
*When:* performing a GET operation on the `.../dggs/{dggrsId}/zones/{zoneID}/data` resource with supported media type specified in the `Accept:` header (e.g., `Accept: application/json` for DGGS-JSON) +
*Then:* (assert that all parts of the requirement are fully satisfied)
====

=== Conformance Class "Data Subsetting"

[[conf_data-subsetting,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-subsetting]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-subsetting
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-subsetting
classification:: Target Type:Web API
abstract-test:: /conf/data-subsetting/subset
abstract-test:: /conf/data-subsetting/datetime
abstract-test:: /conf/data-subsetting/properties
abstract-test:: /conf/data-subsetting/exclude-properties
====

==== Abstract Test for Requirement Parameter `subset`

[[conf_data-subsetting_subset,/conf/data-subsetting/subset]]
[abstract_test]
====
[%metadata]
identifier:: /conf/data-subsetting/subset
target:: /req/data-subsetting/subset
test-purpose:: Verify that the Implementation supports specifying a multi-dimensional subset for the zone data being retrieved
test-method::
+
--
*Given:* a DGGRS zone data resource identified from a `[ogc-rel:dggrs-zone-data]` link template within a DGGRS description resource, replacing the `{zoneId}` variable with a known valid identifier for the DGGRS which successfully passed the `/conf/data-retrieval` abstract test +
*When:* performing a GET operation on the `.../dggs/{dggrsId}/zones/{zoneID}/data` resource with a supported media type and a `subset` parameter identifying an additional dimension not part of the DGGRS supported by the collection +
*Then:* (assert that all parts of the requirement are fully satisfied)
====

==== Abstract Test for Requirement Parameter `datetime`

[[conf_data-subsetting_datetime,/conf/data-subsetting/datetime]]
[abstract_test]
====
[%metadata]
identifier:: /conf/data-subsetting/datetime
target:: /req/data-subsetting/datetime
test-purpose:: Verify that the Implementation supports specifying a time instant or interval for which to retrieve data from a zone for a non-temporal DGGS
test-method::
+
--
*Given:* a DGGRS zone data resource identified from a `[ogc-rel:dggrs-zone-data]` link template within a DGGRS description resource, replacing the `{zoneId}` variable with a known valid identifier for the DGGRS which successfully passed the `/conf/data-retrieval` abstract test +
*When:* performing a GET operation on the `.../dggs/{dggrsId}/zones/{zoneID}/data` resource with a supported media type and a `datetime` parameter identifying a temporal dimension not part of the DGGRS supported by the collection +
*Then:* (assert that all parts of the requirement are fully satisfied)
====

==== Abstract Test for Requirement Parameter `properties`

[[conf_data-subsetting_properties,/conf/data-subsetting/properties]]
[abstract_test]
====
[%metadata]
identifier:: /conf/data-subsetting/properties
target:: /req/data-subsetting/properties
test-purpose:: Verify that the Implementation supports specifying fields to include when retrieving zone data
test-method::
+
--
*Given:* a DGGRS zone data resource identified from a `[ogc-rel:dggrs-zone-data]` link template within a DGGRS description resource, replacing the `{zoneId}` variable with a known valid identifier for the DGGRS which successfully passed the `/conf/data-retrieval` abstract test +
*When:* performing a GET operation on the `.../dggs/{dggrsId}/zones/{zoneID}/data` resource with a supported media type and a `properties` parameter identifying one or more field defined in the collection's logical schema +
*Then:* (assert that all parts of the requirement are fully satisfied)
====

==== Abstract Test for Requirement Parameter `exclude-properties`

[[conf_data-subsetting_exclude-properties,/conf/data-subsetting/exclude-properties]]
[abstract_test]
====
[%metadata]
identifier:: /conf/data-subsetting/exclude-properties
target:: /req/data-subsetting/exclude-properties
test-purpose:: Verify that the Implementation supports including all but specific fields when retrieving zone data
test-method::
+
--
*Given:* a DGGRS zone data resource identified from a `[ogc-rel:dggrs-zone-data]` link template within a DGGRS description resource, replacing the `{zoneId}` variable with a known valid identifier for the DGGRS which successfully passed the `/conf/data-retrieval` abstract test +
*When:* performing a GET operation on the `.../dggs/{dggrsId}/zones/{zoneID}/data` resource with a supported media type and a `exclude-properties` parameter identifying one or more field defined in the collection's logical schema +
*Then:* (assert that all parts of the requirement are fully satisfied)
====

=== Conformance Class "Data Custom Depths"

[[conf_data-custom-depths,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-custom-depths]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-custom-depths
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-custom-depths
classification:: Target Type:Web API
abstract-test:: /conf/data-custom-depths/zone-depth
====

==== Abstract Test for Requirement Parameter `zone-depth`

[[conf_data-custom-depths_zone-depth,/conf/data-custom-depths/zone-depth]]
[abstract_test]
====
[%metadata]
identifier:: /conf/data-custom-depths/zone-depth
target:: /req/data-custom-depths/zone-depth
test-purpose:: Verify that the Implementation supports a parameter to specify the DGGS refinement levels beyond the specified DGGS zone’s refinement level to include in the response, when retrieving data for that zone
test-method::
+
--
*Given:* a DGGRS zone data resource identified from a `[ogc-rel:dggrs-zone-data]` link template within a DGGRS description resource, replacing the `{zoneId}` variable with a known valid identifier for the DGGRS which successfully passed the `/conf/data-retrieval` abstract test +
*When:* performing a GET operation on the `.../dggs/{dggrsId}/zones/{zoneID}/data` resource with a supported media type and a `zone-depth` parameter identifying the relative depth at which to retrieve the data +
*Then:* (assert that all parts of the requirement are fully satisfied)
====

=== Conformance Class "Filtering Zone Data with CQL2"

[[conf_data-cql2-filter,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-cql2-filter]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-cql2-filter
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-cql2-filter
classification:: Target Type:Web API
abstract-test:: /conf/data-cql2-filter/filter
====

==== Abstract Test for Requirement Parameter `filter` (for zone data)

[[conf_data-cql2-filter_filter,/conf/data-cql2-filter/filter]]
[abstract_test]
====
[%metadata]
identifier:: /conf/data-cql2-filter/filter
target:: /req/data-cql2-filter/filter
test-purpose:: Verify that the Implementation supports specifying a CQL2 expression filtering the data returned from a zone data request
test-method::
+
--
*Given:* a DGGRS zone data resource identified from a `[ogc-rel:dggrs-zone-data]` link template within a DGGRS description resource, replacing the `{zoneId}` variable with a known valid identifier for the DGGRS which successfully passed the `/conf/data-retrieval` abstract test +
*When:* performing a GET operation on the `.../dggs/{dggrsId}/zones/{zoneID}/data` resource with a supported media type and a `filter` parameter identifying a CQL2 expression to filter the data being retrieved +
*Then:* (assert that all parts of the requirement are fully satisfied)
====

=== Conformance Class "Zone Query"

[[conf_zone-query,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-query]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-query
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/zone-query
classification:: Target Type:Web API
abstract-test:: /conf/zone-query/zones-list
abstract-test:: /conf/zone-query/json-response
abstract-test:: /conf/zone-query/zone-level
abstract-test:: /conf/zone-query/compact-zones
abstract-test:: /conf/zone-query/parent-zone
abstract-test:: /conf/zone-query/bbox
abstract-test:: /conf/zone-query/bbox-crs
abstract-test:: /conf/zone-query/subset
abstract-test:: /conf/zone-query/subset-crs
abstract-test:: /conf/zone-query/datetime
====

==== Abstract Test for Requirement Listing zones

[[conf_zone-query_zones-list,/conf/zone-query/zones-list]]
[abstract_test]
====
[%metadata]
identifier:: /conf/zone-query/zones-list
target:: /req/zone-query/zones-list
test-purpose:: Verify that the Implementation supports querying DGGRS zones
test-method::
+
--
*Given:* a DGGRS zones query resource identified from a `[ogc-rel:dggrs-zone-query]` link +
*When:* performing a GET operation on the `.../dggs/{dggrsId}/zones` resource with supported media type specified in the `Accept:` header (e.g., `Accept: application/json` for a JSON zone list) +
*Then:* (assert that all parts of the requirement are fully satisfied)
====

==== Abstract Test for Requirement JSON zone list encoding

[[conf_zone-query_json-response,/conf/zone-query/json-response]]
[abstract_test]
====
[%metadata]
identifier:: /conf/zone-query/json-response
target:: /req/zone-query/json-response
test-purpose:: Verify that the Implementation supports returning a list of DGGS zones encoded as JSON
test-method::
+
--
*Given:* a DGGRS zones query resource identified from a `[ogc-rel:dggrs-zone-query]` link +
*When:* performing a GET operation on the `.../dggs/{dggrsId}/zones` resource with an `application/json` media type specified in the `Accept:` header +
*Then:* (assert that all parts of the requirement are fully satisfied)
====

==== Abstract Test for Requirement parameter `zone-level`

[[conf_zone-query_zone-level,/conf/zone-query/zone-level]]
[abstract_test]
====
[%metadata]
identifier:: /conf/zone-query/zone-level
target:: /req/zone-query/zone-level
test-purpose:: Verify that the Implementation supports specifying a level at which to return a list of DGGS zones using a `zone-level` query parameter
test-method::
+
--
*Given:* a DGGRS zones query resource identified from a `[ogc-rel:dggrs-zone-query]` link which passed the `/zone-query/zones-list` abstract test +
*When:* performing a GET operation on the `.../dggs/{dggrsId}/zones` resource with a `zone-level` parameter +
*Then:* (assert that all parts of the requirement are fully satisfied)
====

==== Abstract Test for Requirement parameter `compact-zones`

[[conf_zone-query_compact-zones,/conf/zone-query/compact-zones]]
[abstract_test]
====
[%metadata]
identifier:: /conf/zone-query/compact-zones
target:: /req/zone-query/compact-zones
test-purpose:: Verify that the Implementation supports specifying whether to retrieve a list of DGGS zones using a compact-zones parameter
test-method::
+
--
*Given:* a DGGRS zones query resource identified from a `[ogc-rel:dggrs-zone-query]` link which passed the `/zone-query/zones-list` abstract test +
*When:* performing GET operations on the `.../dggs/{dggrsId}/zones` resource with a `compact-zones` parameter set to true and false +
*Then:* (assert that all parts of the requirement are fully satisfied)
====

==== Abstract Test for Requirement parameter `parent-zone`

[[conf_zone-query_parent-zone,/conf/zone-query/parent-zone]]
[abstract_test]
====
[%metadata]
identifier:: /conf/zone-query/parent-zone
target:: /req/zone-query/parent-zone
test-purpose:: Verify that the Implementation supports specifying a parent zone within which to restrict zone listing using a `parent-zone` query parameter
test-method::
+
--
*Given:* a DGGRS zones query resource identified from a `[ogc-rel:dggrs-zone-query]` link which passed the `/zone-query/zones-list` abstract test +
*When:* performing GET operations on the `.../dggs/{dggrsId}/zones` resource with a `parent-zone` parameter set to a valid zone identifier for the selected DGGRS +
*Then:* (assert that all parts of the requirement are fully satisfied)
====

==== Abstract Test for Requirement parameter `bbox`

[[conf_zone-query_bbox,/conf/zone-query/bbox]]
[abstract_test]
====
[%metadata]
identifier:: /conf/zone-query/bbox
target:: /req/zone-query/bbox
test-purpose:: Verify that the Implementation supports specifying a spatial bounding box for which to return a list of DGGS zones
test-method::
+
--
*Given:* a DGGRS zones query resource identified from a `[ogc-rel:dggrs-zone-query]` link which passed the `/zone-query/zones-list` abstract test +
*When:* performing GET operations on the `.../dggs/{dggrsId}/zones` resource with a `bbox` parameter set to a geospatial extent in OGC:CRS84 within the extent of the dataset or collection being tested +
*Then:* (assert that all parts of the requirement are fully satisfied)
====

==== Abstract Test for Requirement parameter `bbox-crs`

[[conf_zone-query_bbox-crs,/conf/zone-query/bbox-crs]]
[abstract_test]
====
[%metadata]
identifier:: /conf/zone-query/bbox-crs
target:: /req/zone-query/bbox-crs
test-purpose:: Verify that the Implementation supports specifying the CRS used for the bbox parameter using the bbox-crs parameter
test-method::
+
--
*Given:* a DGGRS zones query resource identified from a `[ogc-rel:dggrs-zone-query]` link which passed the `/zone-query/zones-list` abstract test and a collection +
*When:* performing GET operations on the `.../dggs/{dggrsId}/zones` resource with a `bbox` parameter set to a geospatial extent in either OGC:CRS84 or in the `storageCrs` of the dataset or collection within the extent of the dataset or collection being tested and a `bbox-crs` set to that CRS in which the extent is specified +
*Then:* (assert that all parts of the requirement are fully satisfied)
====

==== Abstract Test for Requirement parameter `subset`

[[conf_zone-query_subset,/conf/zone-query/subset]]
[abstract_test]
====
[%metadata]
identifier:: /conf/zone-query/subset
target:: /req/zone-query/subset
test-purpose:: Verify that the Implementation supports specifying a spatial bounding box for which to return a list of DGGS zones
test-method::
+
--
*Given:* a DGGRS zones query resource identified from a `[ogc-rel:dggrs-zone-query]` link which passed the `/zone-query/zones-list` abstract test +
*When:* performing GET operations on the `.../dggs/{dggrsId}/zones` resource with a `subset` parameter set to a geospatial extent in OGC:CRS84 within the extent of the dataset or collection being tested, time for temporal dataset or collection, and another dimension (e.g., atmospheric pressure level) if supported by the dataset or collection +
*Then:* (assert that all parts of the requirement are fully satisfied)
====

==== Abstract Test for Requirement parameter `subset-crs`

[[conf_zone-query_subset-crs,/conf/zone-query/subset-crs]]
[abstract_test]
====
[%metadata]
identifier:: /conf/zone-query/subset-crs
target:: /req/zone-query/subset-crs
test-purpose:: Verify that the Implementation supports specifying the CRS used for the bbox parameter using the bbox-crs parameter
test-method::
+
--
*Given:* a DGGRS zones query resource identified from a `[ogc-rel:dggrs-zone-query]` link which passed the `/zone-query/zones-list` abstract test and a collection +
*When:* performing GET operations on the `.../dggs/{dggrsId}/zones` resource with a `subset` parameter set to a geospatial extent in either OGC:CRS84 or in the `storageCrs` of the dataset or collection within the extent of the dataset or collection being tested and a `subset-crs` set to that CRS in which the extent is specified +
*Then:* (assert that all parts of the requirement are fully satisfied)
====

==== Abstract Test for Requirement parameter `datetime`

[[conf_zone-query_datetime,/conf/zone-query/datetime]]
[abstract_test]
====
[%metadata]
identifier:: /conf/zone-query/datetime
target:: /req/zone-query/datetime
test-purpose:: Verify that the Implementation supports specifying a multi-dimensional subset for which to return a list of DGGS zones
test-method::
+
--
*Given:* a DGGRS zones query resource identified from a `[ogc-rel:dggrs-zone-query]` link which passed the `/zone-query/zones-list` abstract test +
*When:* performing GET operations on the `.../dggs/{dggrsId}/zones` resource with a `datetime` parameter set to a temporal extent within the dataset or collection's temporal extent +
*Then:* (assert that all parts of the requirement are fully satisfied)
====

=== Conformance Class "Filtering Zone Queries with CQL2"

[[conf_zone-query-cql2-filter,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-query-cql2-filter]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-query-cql2-filter
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/zone-query-cql2-filter
classification:: Target Type:Web API
abstract-test:: /conf/zone-query-cql2-filter/filter
====

==== Abstract Test for Requirement parameter `filter` (for zone queries)

[[conf_zone-query_filter,/conf/zone-query-cql2-filter/filter]]
[abstract_test]
====
[%metadata]
identifier:: /conf/zone-query-cql2-filter/filter
target:: /req/zone-query-cql2-filter/filter
test-purpose:: Verify that the Implementation supports specifying a CQL2 expression filtering the zones returned from a zone query
test-method::
+
--
*Given:* a DGGRS zones query resource identified from a `[ogc-rel:dggrs-zone-query]` link which passed the `/zone-query/zones-list` abstract test +
*When:* performing GET operations on the `.../dggs/{dggrsId}/zones` resource with a `filter` parameter set to a CQL2 expression filtering zones to return +
*Then:* (assert that all parts of the requirement are fully satisfied)
====

=== Conformance Class "Root DGGS"

[[conf_root-dggs,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/root-dggs]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/root-dggs
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/root-dggs
classification:: Target Type:Web API
abstract-test:: /conf/root-dggs/dggs
====

==== Abstract Test for Requirement Root DGGS

[[conf_root-dggs_dggs,/conf/root-dggs/dggs]]
[abstract_test]
====
[%metadata]
identifier:: /conf/root-dggs/dggs
target:: /req/root-dggs/dggs
test-purpose:: Verify that the Implementation supports API/dataset-wide DGGS resources
test-method::
+
--
*Given:* an implementation declaring conformance to Root DGGS +
*When:* testing the `/conf/core` conformance class as well the `/conf/zone-query` and/or the `/conf/data-retrieval` conformance classes for the DGGS resources originating from the root origin at `/dggs` +
*Then:* (assert that all parts of the requirement are fully satisfied)
====

=== Conformance Class "Collection DGGS"

[[conf_collection-dggs,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/collection-dggs]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/collection-dggs
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/collection-dggs
classification:: Target Type:Web API
abstract-test:: /conf/collection-dggs/dggs
====

==== Abstract Test for Requirement Collection DGGS

[[conf_collection-dggs_dggs,/conf/collection-dggs/dggs]]
[abstract_test]
====
[%metadata]
identifier:: /conf/collection-dggs/dggs
target:: /req/collection-dggs/dggs
test-purpose:: Verify that the Implementation supports collection DGGS resources
test-method::
+
--
*Given:* an implementation declaring conformance to Collection DGGS +
*When:* testing the `/conf/core` conformance class as well the `/conf/zone-query` and/or the `/conf/data-retrieval` conformance classes for the DGGS resources originating from collections at `/collections/{collectoinId}/dggs` +
*Then:* (assert that all parts of the requirement are fully satisfied)
====

=== Conformance Class "DGGS-JSON zone data encoding"

[[conf_data-json,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-json]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-json
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-json
classification:: Target Type:Web API
abstract-test:: /conf/data-json/content
====

==== Abstract Test for Requirement DGGS-JSON Zone data encoding

[[conf_data-json_content,/conf/data-json/content]]
[abstract_test]
====
[%metadata]
identifier:: /conf/data-json/content
target:: /req/data-json/content
test-purpose:: Verify that the Implementation supports encoding zone data as DGGS-JSON
test-method::
+
--
*Given:* a DGGRS zone data resource identified from a `[ogc-rel:dggrs-zone-data]` link template within a DGGRS description resource, replacing the `{zoneId}` variable with a known valid identifier for the DGGRS, not beyond the `maxRefinementLevel` if one is specified +
*When:* performing a GET operation on the `.../dggs/{dggrsId}/zones/{zoneID}/data` resource with media type `application/json` for DGGS-JSON +
*Then:* +
- assert that every 200 response of the server for zone data with the media type `application/json` is a JSON document representing the data values for all selected fields of each included sub-zone. +
- assert that the schema for the JSON document follows the JSON Schema for DGGS-JSON described in <</req/data-json/content>> +
- assert that every zone depth requested is using the `zone-depth` parameter included in the response. +
- assert thatt at every depth, each individual value corresponds exactly to the data sampled representative of that sub-zone. +
- assert that the list of data values follows the default zone order as specified by the Discrete Global Grid Reference System (for example based on a scanline or space-filling curved defined therein) for which the request is made. +
- assert that Null values use the `null` JSON value. 
====

=== Conformance Class "DGGS-UBJSON zone data encoding"

[[conf_data-ubjson,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-ubjson]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-ubjson
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-ubjson
classification:: Target Type:Web API
abstract-test:: /conf/data-ubjson/content
====

==== Abstract Test for Requirement DGGS-UBJSON Zone data encoding

[[conf_data-ubjson_content,/conf/data-ubjson/content]]
[abstract_test]
====
[%metadata]
identifier:: /conf/data-ubjson/content
target:: /req/data-ubjson/content
test-purpose:: Verify that the Implementation supports encoding zone data as DGGS-UBJSON
test-method::
+
--
*Given:* a DGGRS zone data resource identified from a `[ogc-rel:dggrs-zone-data]` link template within a DGGRS description resource, replacing the `{zoneId}` variable with a known valid identifier for the DGGRS, not beyond the `maxRefinementLevel` if one is specified +
*When:* performing a GET operation on the `.../dggs/{dggrsId}/zones/{zoneID}/data` resource with media type `application/ubjson` for DGGS-JSON +
*Then:* +
- assert that every 200 response of the server for zone data with the media type `application/ubjson` is a https://ubjson.org/[Universal Binary JSON] document representing the data values for all selected fields for a single zone. +
- assert that the schema for the UBJSON document follows the same JSON Schema as for DGGS-JSON described above. +
- assert that every zone depth requested using the `zone-depth` parameter is included in the response. +
- assert that at every depth, each individual value corresponds exactly to the data sampled representative of that zone geometry. +
- assert that the list of data values follows the default zone order as specified by the Discrete Global Grid Reference System (for example based on a scanline or space-filling curved defined therein) for which the request is made. +
- assert that Null values use the `null` JSON value.
====

=== Conformance Class "DGGS-JSON-FG zone data encoding"

[[conf_data-dggs-jsonfg,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-dggs-jsonfg]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-dggs-jsonfg
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-dggs-jsonfg
classification:: Target Type:Web API
abstract-test:: /conf/data-dggs-jsonfg/content
====

==== Abstract Test for Requirement DGGS-JSON-FG Zone data encoding

[[conf_data-dggs-jsonfg_content,/conf/data-dggs-jsonfg/content]]
[abstract_test]
====
[%metadata]
identifier:: /conf/data-dggs-jsonfg/content
target:: /req/data-dggs-jsonfg/content
test-purpose:: Verify that the Implementation supports encoding zone data as DGGS-JSON-FG
test-method::
+
--
*Given:* a DGGRS zone data resource identified from a `[ogc-rel:dggrs-zone-data]` link template within a DGGRS description resource, replacing the `{zoneId}` variable with a known valid identifier for the DGGRS, not beyond the `maxRefinementLevel` if one is specified +
*When:* performing a GET operation on the `.../dggs/{dggrsId}/zones/{zoneID}/data` resource with media type `application/geo+json` and a `profile` query parameter value of `jsonfg-dggs`, `jsonfg-dggs-plus`, `jsonfg-dggs-zoneids` or `jsonfg-dggs-zoneids-plus` for DGGS-JSON-FG +
*Then:* +
- assert that the implementation supports zone data requests negotiating an `application/geo+json` media type combined with a `profile` query parameter with a value of `jsonfg-dggs`, `jsonfg-dggs-plus`, `jsonfg-dggs-zoneids` or `jsonfg-dggs-zoneids-plus` allowing a client to request a DGGS-JSON-FG response. +
- assert that every 200 response of the server for DGGS-JSON-FG zone data requests is an extended https://docs.ogc.org/DRAFTS/21-045r1.html[Features & Geometry JSON] (JSON-FG) document representing the vector features within the requested zone. +
- assert that the JSON document follows the JSON Schema for JSON-FG, with geometry stored in a `dggsPlace` property mirroring the JSON-FG `place` schema and supporting all of the same feature types, but where `coordinates` use sub-zone indices (for `profile=jsonfg-dggs` or `jsonfg-dggs-plus`) or global textual zone identifiers (for `profile=jsonfg-dggs-zoneids` or `jsonfg-dggs-zoneids-plus`) as described in later parts of this requirement. +
- assert that for `profile=jsonfg-dggs-plus` and `jsonfg-dggs-zoneids-plus`, the JSON document also includes geometry stored in `geometry` or `place` using traditional coordinate reference system coordinates for compatibility. +
- assert that the JSON document additionally contains a `dggrs` property set to the URI or CURIEs of the DGGRS of the response, which replaces the `coordRefSys` property and concept. +
- assert that the JSON document additionally contains a `zoneId` property indicating the requested reference zone. +
- assert that the JSON document additionally contains a `depth` property corresponding to the relative zone depth (as specified in the single depth format of the OGC API - DGGS `zone-depth` parameter for zone data retrieval), determining how coordinates are resolved from sub-zone indices (in the case of `profile=jsonfg-dggs` and `jsonfg-dggs-plus`), and as a result, their precision. +
- assert that for `profile=jsonfg-dggs` and `jsonfg-dggs-plus`, the JSON document contains a `dggsPlace` property specifying geometry using local sub-zone indices ranging from 1 to the number of sub-zones within the reference parent zone at the declared depth, based on the deterministic sub-zone order of the DGGRS. +
- assert that for `profile=jsonfg-dggs-zoneids` and `jsonfg-dggs-zoneids-plus`, the JSON document contains a `dggsPlace` property specifying geometry using global textual zone identifiers (as defined in the DGGRS zone indexing reference system) at the declared depth. +
- assert that when all spatial coordinates are dimensions of the DGGRS, the array of coordinates including the square brackets are replaced by the local index or global identifier of the sub-zone within which the coordinates are located. +
- assert that when additional spatial coordinates that are not part of the DGGRS, such as elevation above ground for a 2D DGGRS, are needed to define the geometry coordinates, only the coordinates corresponding to DGGRS dimensions are replaced by the local index or global identifier of the sub-zone. +
- assert that only features fully or partly located within the reference zone are included. +
- assert that for feature geometry intersecting the boundaries of the reference zone, the sub-zone within which the intersection is located are included, with a separate single `0` special sub-zone index (in the case of `profile=jsonfg-dggs` and `jsonfg-dggs-plus`) or a `null` value (in the case of `profile=jsonfg-dggs-zoneids` and `jsonfg-dggs-zoneids-plus`) representing all outside points before a point inside, after a point inside, or in between two inside points. +
- assert that for geometry in two or more dimensions with an outside point (identified by a `0` sub-zone index for `profile=jsonfg-dggs` and `jsonfg-dggs-plus`, or `null` for `profile=jsonfg-dggs-zoneids` and `jsonfg-dggs-zoneids-plus`) and which is necessarily between two contour points, the portion of the zone edge(s) between the exit and entry point are considered inside of that contour. +
- assert that the URI of the selected or default DGGS-JSON-FG profile are included in the `links` section of the JSON-FG response.
====

=== Conformance Class "DGGS-UBJSON-FG zone data encoding"

[[conf_data-dggs-ubjsonfg,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-dggs-ubjsonfg]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-dggs-ubjsonfg
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-dggs-ubjsonfg
classification:: Target Type:Web API
abstract-test:: /conf/data-dggs-ubjsonfg/content
====

==== Abstract Test for Requirement DGGS-UBJSON-FG Zone data encoding

[[conf_data-dggs-ubjsonfg_content,/conf/data-dggs-ubjsonfg/content]]
[abstract_test]
====
[%metadata]
identifier:: /conf/data-dggs-ubjsonfg/content
target:: /req/data-dggs-ubjsonfg/content
test-purpose:: Verify that the Implementation supports encoding zone data as DGGS-UBJSON-FG
test-method::
+
--
*Given:* a DGGRS zone data resource identified from a `[ogc-rel:dggrs-zone-data]` link template within a DGGRS description resource, replacing the `{zoneId}` variable with a known valid identifier for the DGGRS, not beyond the `maxRefinementLevel` if one is specified +
*When:* performing a GET operation on the `.../dggs/{dggrsId}/zones/{zoneID}/data` resource with media type `application/geo+ubjson` and a `profile` query parameter value of `jsonfg-dggs`, `jsonfg-dggs-plus`, `jsonfg-dggs-zoneids` or `jsonfg-dggs-zoneids-plus` for DGGS-UBJSON-FG +
*Then:* +
- assert that the Implementation supports zone data requests negotiating an `application/geo+ubjson` media type combined with a `profile` query parameter with a value of `jsonfg-dggs`, `jsonfg-dggs-plus`, `jsonfg-dggs-zoneids` or `jsonfg-dggs-zoneids-plus` allowing a client to request a DGGS-UBJSON-FG response. +
- assert that every 200 response of the server for DGGS-FG-UBJSON zone data requests is a https://ubjson.org/[Universal Binary JSON] document representing the vector features within the requested zone. +
- assert that the content of the UBJSON document follows all the of same requirements as for DGGS-JSON-FG described above.
====

=== Conformance Class "GeoTIFF zone data encoding"

[[conf_data-geotiff,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-geotiff]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-geotiff
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-geotiff
classification:: Target Type:Web API
abstract-test:: /conf/data-geotiff/content
====

==== Abstract Test for Requirement GeoTIFF Zone data encoding

[[conf_data-geotiff_content,/conf/data-geotiff/content]]
[abstract_test]
====
[%metadata]
identifier:: /conf/data-geotiff/content
target:: /req/data-geotiff/content
test-purpose:: Verify that the Implementation supports encoding zone data as GeoTIFF
test-method::
+
--
*Given:* a DGGRS zone data resource identified from a `[ogc-rel:dggrs-zone-data]` link template within a DGGRS description resource, replacing the `{zoneId}` variable with a known valid identifier for the DGGRS, not beyond the `maxRefinementLevel` if one is specified +
*When:* performing a GET operation on the `.../dggs/{dggrsId}/zones/{zoneID}/data` resource with media type `image/tiff; application=geotiff` for GeoTIFF +
*Then:* (assert that all parts of the requirement are fully satisfied)
====

=== Conformance Class "GeoJSON zone data encoding"

[[conf_data-geojson,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-geojson]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-geojson
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-geojson
classification:: Target Type:Web API
abstract-test:: /conf/data-geojson/content
====

==== Abstract Test for Requirement GeoJSON Zone data encoding

[[conf_data-geojson_content,/conf/data-geojson/content]]
[abstract_test]
====
[%metadata]
identifier:: /conf/data-geojson/content
target:: /req/data-geojson/content
test-purpose:: Verify that the Implementation supports encoding zone data as GeoJSON
test-method::
+
--
*Given:* a DGGRS zone data resource identified from a `[ogc-rel:dggrs-zone-data]` link template within a DGGRS description resource, replacing the `{zoneId}` variable with a known valid identifier for the DGGRS, not beyond the `maxRefinementLevel` if one is specified +
*When:* performing a GET operation on the `.../dggs/{dggrsId}/zones/{zoneID}/data` resource with media type `application/geo+json` for GeoJSON +
*Then:* (assert that all parts of the requirement are fully satisfied)
====

=== Conformance Class "netCDF zone data encoding"

[[conf_data-netcdf,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-netcdf]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-netcdf
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-netcdf
classification:: Target Type:Web API
abstract-test:: /conf/data-netcdf/content
====

==== Abstract Test for Requirement netCDF Zone data encoding

[[conf_data-netcdf_content,/conf/data-netcdf/content]]
[abstract_test]
====
[%metadata]
identifier:: /conf/data-netcdf/content
target:: /req/data-netcdf/content
test-purpose:: Verify that the Implementation supports encoding zone data as netCDF
test-method::
+
--
*Given:* a DGGRS zone data resource identified from a `[ogc-rel:dggrs-zone-data]` link template within a DGGRS description resource, replacing the `{zoneId}` variable with a known valid identifier for the DGGRS, not beyond the `maxRefinementLevel` if one is specified +
*When:* performing a GET operation on the `.../dggs/{dggrsId}/zones/{zoneID}/data` resource with media type `application/netcdf` for netCDF +
*Then:* +
- assert that every 200 response of the server for zone data with the media type `application/netcdf` is a netCDF file representing the data values for all selected fields for a single zone. +
- assert that the response is encoded using a netCDF encoding extension, such as the https://portal.ogc.org/files/?artifact_id=43734[NetCDF classic and 64-bit offset format], or netCDF version 4 based on
https://docs.ogc.org/is/18-043r3/18-043r3.html[OGC HDF5]. +
- assert that for a DGGS-optimized profile (`netcdf3-dggs`, `netcdf3-dggs-zoneids`, `netcdf4-dggs`, `netcdf3-dggs-zoneids`), the profile URI, the global identifier of the parent zone and a URI or link to the DGGRS definition is included as metadata. +
- assert that for a DGGS-optimized profile, coordinates along one dimension corresponds to sub-zones, either as global zone identifiers (`netcdf3-dggs-zoneids`, `netcdf4-dggs-zoneids`) or local sub-zone indices following the deterministic DGGRS sub-zone order (`netcdf3-dggs`, `netcdf4-dggs`), while spatiotemporal dimensions of the DGGRS is not defined as separate dimensions. +
- assert that for non-DGGS-optimized profiles, if the netCDF data incorporates georeferencing information, this information is consistent with the DGGRS Zone ID. +
- assert that for non-DGGS-optimized profiles, if the zone geometry is not rectilinear, the closest bounding rectangle (or volume) is used for referencing the data. +
- assert that for non-DGGS-optimized profiles, a distinct value for each sub-zone implied from the requested `zone-depth` corresponds to at least one distinct cell value in the response.
====

=== Conformance Class "Zarr zone data encoding"

[[conf_data-zarr,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-zarr]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-zarr
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-zarr
classification:: Target Type:Web API
abstract-test:: /conf/data-zarr/content
====

==== Abstract Test for Requirement Zarr Zone data encoding

[[conf_data-zarr_content,/conf/data-zarr/content]]
[abstract_test]
====
[%metadata]
identifier:: /conf/data-zarr/content
target:: /req/data-zarr/content
test-purpose:: Verify that the Implementation supports encoding zone data as zipped Zarr 2
test-method::
+
--
*Given:* a DGGRS zone data resource identified from a `[ogc-rel:dggrs-zone-data]` link template within a DGGRS description resource, replacing the `{zoneId}` variable with a known valid identifier for the DGGRS, not beyond the `maxRefinementLevel` if one is specified +
*When:* performing a GET operation on the `.../dggs/{dggrsId}/zones/{zoneID}/data` resource with media type `application/zarr+zip` for zipped Zarr 2 +
*Then:* (assert that all parts of the requirement are fully satisfied)
====

=== Conformance Class "CoverageJSON zone data encoding"

[[conf_data-coveragejson,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-coveragejson]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-coveragejson
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-coveragejson
classification:: Target Type:Web API
abstract-test:: /conf/data-coveragejson/content
====

==== Abstract Test for Requirement CoverageJSON Zone data encoding

[[conf_data-coveragejson_content,/conf/data-coveragejson/content]]
[abstract_test]
====
[%metadata]
identifier:: /conf/data-coveragejson/content
target:: /req/data-coveragejson/content
test-purpose:: Verify that the Implementation supports encoding zone data as CoverageJSON
test-method::
+
--
*Given:* a DGGRS zone data resource identified from a `[ogc-rel:dggrs-zone-data]` link template within a DGGRS description resource, replacing the `{zoneId}` variable with a known valid identifier for the DGGRS, not beyond the `maxRefinementLevel` if one is specified +
*When:* performing a GET operation on the `.../dggs/{dggrsId}/zones/{zoneID}/data` resource with media type `application/prs.coverage+json` for CoverageJSON +
*Then:* (assert that all parts of the requirement are fully satisfied)
====

=== Conformance Class "JPEG XL zone data encoding"

[[conf_data-jpegxl,/conf/data-jpegxl]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-jpegxl
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-jpegxl
classification:: Target Type:Web API
abstract-test:: /conf/data-jpegxl/content
====

==== Abstract Test for Requirement JPEG XL Zone data encoding

[[conf_data-jpegxl_content,/conf/data-jpegxl/content]]
[abstract_test]
====
[%metadata]
identifier:: /conf/data-jpegxl/content
target:: /req/data-jpegxl/content
test-purpose:: Verify that the Implementation supports encoding zone data as JPEG XL
test-method::
+
--
*Given:* a DGGRS zone data resource identified from a `[ogc-rel:dggrs-zone-data]` link template within a DGGRS description resource, replacing the `{zoneId}` variable with a known valid identifier for the DGGRS, not beyond the `maxRefinementLevel` if one is specified +
*When:* performing a GET operation on the `.../dggs/{dggrsId}/zones/{zoneID}/data` resource with media type `image/jxl` for JPEG XL +
*Then:* (assert that all parts of the requirement are fully satisfied)
====

=== Conformance Class "PNG zone data encoding "

[[conf_data-png,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-png]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-png
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-png
classification:: Target Type:Web API
abstract-test:: /conf/data-png/content
====

==== Abstract Test for Requirement PNG Zone data encoding

[[conf_data-png_content,/conf/data-png/content]]
[abstract_test]
====
[%metadata]
identifier:: /conf/data-png/content
target:: /req/data-png/content
test-purpose:: Verify that the Implementation supports encoding zone data as PNG
test-method::
+
--
*Given:* a DGGRS zone data resource identified from a `[ogc-rel:dggrs-zone-data]` link template within a DGGRS description resource, replacing the `{zoneId}` variable with a known valid identifier for the DGGRS, not beyond the `maxRefinementLevel` if one is specified +
*When:* performing a GET operation on the `.../dggs/{dggrsId}/zones/{zoneID}/data` resource with media type `image/png` for PNG +
*Then:* (assert that all parts of the requirement are fully satisfied)
====

=== Conformance Class "HTML zone list encoding"

[[conf_zone-html,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-html]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-html
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/zone-html
classification:: Target Type:Web API
abstract-test:: /conf/zone-html/content
====

==== Abstract Test for Requirement HTML zone list encoding

[[conf_zone-html_content,/conf/zone-html/content]]
[abstract_test]
====
[%metadata]
identifier:: /conf/zone-html/content
target:: /req/zone-html/content
test-purpose:: Verify that the Implementation supports encoding zone lists as HTML
test-method::
+
--
*Given:* a DGGRS zones query resource identified from a `[ogc-rel:dggrs-zone-query]` link +
*When:* performing a GET operation on the `.../dggs/{dggrsId}/zones` resource with `text/html` media type for HTML +
*Then:* (assert that all parts of the requirement are fully satisfied)
====

=== Conformance Class "Binary 64-bit integer zone list encoding"

[[conf_zone-uint64,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-uint64]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-uint64
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/zone-uint64
classification:: Target Type:Web API
abstract-test:: /conf/zone-uint64/content
====

==== Abstract Test for Requirement Binary 64-bit integer zone list encoding

[[conf_zone-uint64_content,/conf/zone-uint64/content]]
[abstract_test]
====
[%metadata]
identifier:: /conf/zone-uint64/content
target:: /req/zone-uint64/content
test-purpose:: Verify that the Implementation supports encoding zone lists as 64-bit unsigned integer
test-method::
+
--
*Given:* a DGGRS zones query resource identified from a `[ogc-rel:dggrs-zone-query]` link +
*When:* performing a GET operation on the `.../dggs/{dggrsId}/zones` resource with `application/x-binary` media type for 64-bit unsigned integers +
*Then:* (assert that all parts of the requirement are fully satisfied)
====

=== Conformance Class "GeoJSON zone list encoding "

[[conf_zone-geojson,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-geojson]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-geojson
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/zone-geojson
classification:: Target Type:Web API
abstract-test:: /conf/zone-geojson/content
====

==== Abstract Test for Requirement GeoJSON zone list encoding

[[conf_zone-geojson_content,/conf/zone-geojson/content]]
[abstract_test]
====
[%metadata]
identifier:: /conf/zone-geojson/content
target:: /req/zone-geojson/content
test-purpose:: Verify that the Implementation supports encoding zone lists as GeoJSON
test-method::
+
--
*Given:* a DGGRS zones query resource identified from a `[ogc-rel:dggrs-zone-query]` link +
*When:* performing a GET operation on the `.../dggs/{dggrsId}/zones` resource with `application/geo+json` media type for GeoJSON +
*Then:* (assert that all parts of the requirement are fully satisfied)
====

=== Conformance Class "GeoTIFF zone list encoding"

[[conf_zone-geotiff,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-geotiff]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-geotiff
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/zone-geotiff
classification:: Target Type:Web API
abstract-test:: /conf/zone-geotiff/content
====

==== Abstract Test for Requirement GeoTIFF zone list encoding

[[conf_zone-geotiff_content,/conf/zone-geotiff/content]]
[abstract_test]
====
[%metadata]
identifier:: /conf/zone-geotiff/content
target:: /req/zone-geotiff/content
test-purpose:: Verify that the Implementation supports encoding zone lists as GeoTIFF
test-method::
+
--
*Given:* a DGGRS zones query resource identified from a `[ogc-rel:dggrs-zone-query]` link +
*When:* performing a GET operation on the `.../dggs/{dggrsId}/zones` resource with `image/tiff; application=geotiff` media type for GeoTIFF +
*Then:* (assert that all parts of the requirement are fully satisfied)
====

=== Conformance Class "Operation IDs"

[[conf_operation-ids,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/operation-ids]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/operation-ids
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/operation-ids
classification:: Target Type:Web API
abstract-test:: /conf/operation-ids/operation-ids
====

==== Abstract Test for Operation IDs

[[conf_operation-ids_operation-ids,/conf/operation-ids/operation-ids]]
[abstract_test]
====
[%metadata]
identifier:: /conf/operation-ids/operation-ids
target:: /req/operation-ids/operation-ids
test-purpose:: Verify that the correct operation IDs suffixed are used in the API definition to identify DGGS resources
test-method::
+
--
*Given:* an DGGS API implementation providing an API definition with a concept of operation IDs (such as OpenAPI 3.0) +
*When:* inspecting the operations in the API definition for DGGS resources +
*Then:* +
- assert that the operation IDs for DGGS resources correspond to those specified in <<api-operation-id-suffixes>>
====
