[appendix,obligation="normative"]

== Conformance Class Abstract Test Suite

=== Conformance Class "Core"

[[conf_core,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/core]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/core
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/core
classification:: Target Type:Web API
abstract-test:: /conf/core/dggrs-list
abstract-test:: /conf/core/dggrs-info
abstract-test:: /conf/core/zone-info
====

==== Abstract Test for Requirement Listing available DGGRS

[[conf_core_dggrs-list,/conf/core/dggrs-list]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/dggrs-list
target:: /req/core/dggrs-list
test-purpose:: Verify that the implementation supports listing the available DGGRSs
test-method::
+
--
*Given:* a geospatial data resource conforming to the DGGS API Standard, with an API path including `.../dggs` or discovered following a link with relation type `[ogc-rel:dggrs-list]` +
*When:* performing a GET operation on the `.../dggs` resource with an `application/json` media type specified in the `Accept:` header (e.g., `Accept: application/json`) +
*Then:* (assert that all parts of the requirement are fully satisfied)
====

==== Abstract Test for Discrete global grid reference system information

[[conf_core_dggrs-info,/conf/core/dggrs-info]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/dggrs-info
target:: /req/core/dggrs-info
test-purpose:: Verify that the implementation supports retrieving information for a particular DGGRSs
test-method::
+
--
*Given:* a DGGRS resource identified from listing available DGGRS or discovered by following a link with relation type `[ogc-rel:dggrs]` +
*When:* performing a GET operation on the `.../dggs/{dggrsId}` resource with an `application/json` media type specified in the `Accept:` header (e.g., `Accept: application/json`) +
*Then:* (assert that all parts of the requirement are fully satisfied)
====

==== Abstract Test for Retrieving zone information

[[conf_core_zone-info,/conf/core/zone-info]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/zone-info
target:: /req/core/zone-info
test-purpose:: Verify that the implementation supports retrieving information for a particular DGGRS zone
test-method::
+
--
*Given:* a DGGRS zone information resource identified from a `[ogc-rel:dggrs-zone-info]` link template within a DGGRS description resource, replacing the `{zoneId}` variable with a known valid identifier for the DGGRS, not beyond the `maxRefinementLevel` if one is specified +
*When:* performing a GET operation on the `.../dggs/{dggrsId}/zones/{zoneID}` resource with an `application/json` media type specified in the `Accept:` header (e.g., `Accept: application/json`) +
*Then:* (assert that all parts of the requirement are fully satisfied)
====

=== Conformance Class "Data Retrieval"

[[conf_data-retrieval,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-retrieval]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-retrieval
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-retrieval
classification:: Target Type:Web API
abstract-test:: /conf/data-retrieval/zone-data
====

==== Abstract Test for Retrieving data from a zone

[[conf_data-retrieval_zone-data,/conf/data-retrieval/zone-data]]
[abstract_test]
====
[%metadata]
identifier:: /conf/data-retrieval/zone-data
target:: /req/data-retrieval/zone-data
test-purpose:: Verify that the implementation supports retrieving data for a particular DGGRS zone
test-method::
+
--
*Given:* a DGGRS zone data resource identified from a `[ogc-rel:dggrs-zone-data]` link template within a DGGRS description resource, replacing the `{zoneId}` variable with a known valid identifier for the DGGRS, not beyond the `maxRefinementLevel` if one is specified +
*When:* performing a GET operation on the `.../dggs/{dggrsId}/zones/{zoneID}/data` resource with supported media type specified in the `Accept:` header (e.g., `Accept: application/json` for DGGS-JSON) +
*Then:* (assert that all parts of the requirement are fully satisfied)
====

=== Conformance Class "Data Subsetting"

[[conf_data-subsetting,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-subsetting]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-subsetting
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-subsetting
classification:: Target Type:Web API
abstract-test:: /conf/data-retrieval/zone-data
====

=== Conformance Class "Data Custom Depths"

[[conf_data-custom-depths,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-custom-depths]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-custom-depths
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-custom-depths
classification:: Target Type:Web API
====

=== Conformance Class "Filtering Zone Data with CQL2"

[[conf_data-cql2-filter,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-cql2-filter]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-cql2-filter
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-cql2-filter
classification:: Target Type:Web API
====

=== Conformance Class "Zone Query"

[[conf_zone-query,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-query]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-query
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/zone-query
classification:: Target Type:Web API
abstract-test:: /conf/zone-query/zones-list
====

==== Abstract Test for Listing zones

[[conf_zone-query_zones-list,/conf/zone-query/zones-list]]
[abstract_test]
====
[%metadata]
identifier:: /conf/zone-query/zones-list
target:: /req/zone-query/zones-list
test-purpose:: Verify that the implementation supports querying DGGRS zones
test-method::
+
--
*Given:* a DGGRS zones query resource identified from a `[ogc-rel:dggrs-zone-query]` link +
*When:* performing a GET operation on the `.../dggs/{dggrsId}/zones` resource with supported media type specified in the `Accept:` header (e.g., `Accept: application/json` for a JSON zone list) +
*Then:* (assert that all parts of the requirement are fully satisfied)
====

=== Conformance Class "Filtering Zone Queries with CQL2"

[[conf_zone-query-cql2-filter,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-query-cql2-filter]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-query-cql2-filter
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/zone-query-cql2-filter
classification:: Target Type:Web API
====

=== Conformance Class "Root DGGS"

[[conf_root-dggs,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/root-dggs]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/root-dggs
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/root-dggs
classification:: Target Type:Web API
====

=== Conformance Class "Collection DGGS"

[[conf_collection-dggs,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/collection-dggs]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/collection-dggs
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/collection-dggs
classification:: Target Type:Web API
====

=== Conformance Class "DGGS-JSON encoding for Zone Data"

[[conf_data-json,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-json]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-json
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-json
classification:: Target Type:Web API
====

=== Conformance Class "DGGS-UBJSON encoding for Zone Data"

[[conf_data-ubjson,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-ubjson]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-ubjson
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-ubjson
classification:: Target Type:Web API
====

=== Conformance Class "DGGS-FG-JSON encoding for Zone Data"

[[conf_data-dggs-fgjson,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-dggs-fgjson]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-dggs-fgjson
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-dggs-fgjson
classification:: Target Type:Web API
====

=== Conformance Class "DGGS-FG-UBJSON encoding for Zone Data"

[[conf_data-dggs-fgubjson,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-dggs-fgubjson]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-dggs-fgubjson
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-dggs-fgubjson
classification:: Target Type:Web API
====

=== Conformance Class "GeoTIFF encoding for Zone Data"

[[conf_data-geotiff,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-geotiff]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-geotiff
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-geotiff
classification:: Target Type:Web API
====

=== Conformance Class "GeoJSON encoding for Zone Data"

[[conf_data-geojson,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-geojson]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-geojson
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-geojson
classification:: Target Type:Web API
====

=== Conformance Class "FG-JSON encoding for Zone Data"

[[conf_data-fgjson,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-fgjson]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-fgjson
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-fgjson
classification:: Target Type:Web API
====

=== Conformance Class "netCDF encoding for Zone Data"

[[conf_data-netcdf,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-netcdf]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-netcdf
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-netcdf
classification:: Target Type:Web API
====

=== Conformance Class "Zarr encoding for Zone Data"

[[conf_data-zarr,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-zarr]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-zarr
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-zarr
classification:: Target Type:Web API
====

=== Conformance Class "CoverageJSON encoding for Zone Data"

[[conf_data-coveragejson,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-coveragejson]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-coveragejson
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-coveragejson
classification:: Target Type:Web API
====

=== Conformance Class "JPEG XL Encoding for Zone Data"

[[conf_data-jpegxlhttps://www.opengis.net/spec/ogcapi-dggs-1/1.0,/conf/data-jpegxl]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-jpegxl
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-jpegxl
classification:: Target Type:Web API
====

=== Conformance Class "PNG encoding for Zone Data"

[[conf_data-png,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-png]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-png
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-png
classification:: Target Type:Web API
====

=== Conformance Class "JSON encoding for Zone Listing"

[[conf_zone-json,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-json]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-json
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/zone-json
classification:: Target Type:Web API
====

=== Conformance Class "HTML encoding for Zone Listing"

[[conf_zone-html,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-html]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-html
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/zone-html
classification:: Target Type:Web API
====

=== Conformance Class "Binary 64-bit integer encoding for Zone Listing"

[[conf_zone-uint64,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-uint64]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-uint64
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/zone-uint64
classification:: Target Type:Web API
====

=== Conformance Class "GeoJSON encoding for Zone Listing"

[[conf_zone-geojson,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-geojson]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-geojson
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/zone-geojson
classification:: Target Type:Web API
====

=== Conformance Class "FG-JSON encoding for Zone Listing"

[[conf_zone-fgjson,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-fgjson]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-fgjson
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/zone-fgjson
classification:: Target Type:Web API
====

=== Conformance Class "GeoTIFF encoding for Zone Listing"

[[conf_zone-geotiff,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-geotiff]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-geotiff
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/zone-geotiff
classification:: Target Type:Web API
====

=== Conformance Class "Operation IDs"

[[conf_operation-ids,https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/operation-ids]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/operation-ids
target:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/operation-ids
classification:: Target Type:Web API
abstract-test:: /conf/operation-ids/operation-ids
====

==== Abstract Test for Operation IDs

[[conf_operation-ids_operation-ids,/conf/operation-ids/operation-ids]]
[abstract_test]
====
[%metadata]
identifier:: /conf/operation-ids/operation-ids
target:: /req/operation-ids/operation-ids
test-purpose:: Verify that the correct operation IDs suffixed are used in the API definition to identify DGGS resources
test-method::
+
--
*Given:* an DGGS API implementation providing an API definition with a concept of operation IDs (such as OpenAPI 3.0) +
*When:* inspecting the operations in the API definition for DGGS resources +
*Then:* +
- assert that the operation IDs for DGGS resources correspond to those specified in <<api-operation-id-suffixes>>
====
