[[zone-list-encodings-section]]
== Requirements Classes for Encodings of Zone list

The OGC API - DGGS Standard requires supporting a JSON encoding for returning the `../dggs/{dggrsId}/zones` resources, as described in the <<rc_zone-query,Zone Query>> requirement class.
In addition to this JSON encoding, DGGRS Zone Lists can be encoded in any suitable data format, as negotiated by erver and client.
A number of requirements classes are defined for zone list encodings which are expected to be commonly supported in implementations of this Standard.
These requirements classes include:

* <<rc_zone-html,HTML Zone List>>
* <<rc_zone-uint64,64-bit Binary Zone List>>
* <<rc_zone-geojson,GeoJSON Zone List>> -- including support for Features & Geometry JSON (FG-JSON) output as a recommendation
* <<rc_zone-geotiff,GeoTIFF Zone List>>

[[zone_list_media_types]]
=== Media Types (for zone list)

A table of the media types used in the zone list encoding requirements classes defined in this standard follows.

[#api-dggs-zone-list-media-types,reftext='{table-caption} {counter:table-num}']
.Media Types used for zone list encoding requirements classes
[width="90%",cols="2,4"]
|====
^|*Encoding*                ^|*Media type*
|JSON zone list              |application/json
|HTML zone list              |text/html
|Binary 64-bit zone list     |application/x-binary
|GeoJSON / FG-JSON zone list |application/geo+json
|GeoTIFF zone list           |image/tiff; application=geotiff
|====

[[rc_zone-html]]
=== Requirements Class "HTML zone list encoding"

==== Overview

The HTML zone list encoding requirements class defines at a high level the ability to retrieve an HTML response for the DGGRS zone list resource intended primarily for users accessing the API from a Web browser.

The exact content of the HTML response is not prescribed, leaving the flexibility for implementations to choose a preferred approach.

HTML is the core language of the World Wide Web. An API that supports HTML will support browsing the spatial resources with a web browser and will also enable search engines to crawl and index those resources.

include::../requirements/requirements_class_zone_list_html.adoc[]

[[rc_zone-uint64]]
=== Requirements Class "Binary 64-bit integer zone list encoding"

==== Overview

The binary 64-bit integer zone list encoding requirements class defines the ability to retrieve a binary response for the DGGRS zone list resource for
DGGRS whose zone identifiers can be expressed as a single 64-bit integer.

The response consists of a 64-bit integer count of zones, followed by that count of zones, also 64-bit integers.
With compact zones and additional HTTP content encoding compression, this provides an optimal way to exchange DGGRS zone lists.

include::../requirements/requirements_class_zone_list_binary_64bit.adoc[]

[[rc_zone-geojson]]
=== Requirements Class "GeoJSON zone list encoding"

==== Overview

The GeoJSON zone list encoding requirements class defines support for encoding a DGGRS Zone list response according to the https://datatracker.ietf.org/doc/html/rfc7946[GeoJSON specification],
and optionally according to the https://docs.ogc.org/DRAFTS/21-045.html[OGC Features & Geometry JSON (FG-JSON) Standard].

The response is a feature collection where each feature represents a zone in the list.
The geometry of the zone should be polygons or multipolygons (e.g., in the case of zone geometry which must be split on the anti-meridian or pole), or in the case of a 3D DGGRS and an FG-JSON
response polyhedrons, multipolyhedrons, prisms or multiprisms.
The zone identifier is represented in the `id` field of each feature.

While not intended to efficiently exchange zone list, as the response carries the geometry of the zones which could easily be computed client-side which takes considerable bandwidth and is
not necessary for a DGGS client working natively with the same DGGRS, this requirements class provides an easy way to readily visualize the response in a variety of tools.
This requirements class is therefore intended for convenience, demonstration and educational purposes.

include::../requirements/requirements_class_zone_list_geojson.adoc[]

[[rc_zone-geotiff]]
=== Requirements Class "GeoTIFF zone list encoding"

==== Overview

The GeoTIFF zone list encoding requirements class defines support for encoding a DGGRS Zone list response according to the https://docs.ogc.org/is/19-008r4/19-008r4.html[OGC GeoTIFF standard],
intended primarily for DGGRSs with rectangular zones.

The response is a 2D gridded coverage where each cell is a zone in the list, in the coordinate reference system of that DGGRS.

For DGGRSs with non-rectangular zones, the resolution would need to be higher than a single pixel per the most detailed zone to be returned in order to be able to recognize the zone geometry,
and would therefore be very sub-optimal. While for rectangular zones it would be easy to identify zones with a one-to-one correspondence, recognizing non-rectangular zones would be significantly more difficult.

While not intended to efficiently exchange zone list, this requirements class provides an easy way to readily visualize the response in a variety of tools.
This requirements class is therefore intended for convenience, demonstration and educational purposes.

include::../requirements/requirements_class_zone_list_geotiff.adoc[]
