[[zone-data-encodings-section]]
== Requirements Classes for Encodings of Zone data

The OGC API - DGGS Standard does not mandate any particular encoding or format in which to return the `.../dggs/{dggrsId}/zones/{zoneId}/data` resources.
DGGS Zone Data can be encoded in any suitable data format.
However, the Standard does define requirements classes for zone data encodings which are expected to be commonly supported in implementations of this standard.
These requirements classes include:

For data rasterized to DGGRS sub-zones:

* <<rc_data-json,DGGS-JSON Data>>
* <<rc_data-ubjson,DGGS-UBJSON Data>>

Depending on a selected profile, for data either rasterized to DGGRS sub-zones, or rasterized data output readily usable in non-DGGS systems (or to facilitate interoperability with other DGGHs):

* <<rc_data-zarr,Zarr Data>>
* <<rc_data-netcdf,netCDF Data>>
* <<rc_data-coveragejson,CoverageJSON Data>>

For 2D rasterized data output readily usable in non-DGGS systems or to facilitate interoperability with other DGGHs:

* <<rc_data-geotiff,GeoTIFF Data>>
* <<rc_data-jpegxl,JPEG XL Data>>
* <<rc_data-png,PNG Data>>

For vector features whose geometry coordinates are quantized to DGGRS sub-zones:

* <<rc_data-dggs-jsonfg,DGGS-JSON-FG Data>>
* <<rc_data-dggs-ubjsonfg,DGGS-UBJSON-FG Data>>

For vector features output readily usable in non-DGGS systems or to facilitate interoperability with other DGGHs:

* <<rc_data-geojson,GeoJSON Data>> -- including support for Features & Geometry JSON (JSON-FG) output as a recommendation

[[zone_data_media_types]]
=== Media Types (for zone data)

A table of the media types used in the encoding of the Zone Data requirements classes defined in this Standard follows.

[#api-dggs-zone-data-media-types,reftext='{table-caption} {counter:table-num}']
.Media Types used for zone data encoding requirements classes
[width="90%",cols="2,4"]
|====
^|*Encoding*              ^|*Media type*
|DGGS-JSON zone data      |application/json
|DGGS-UBJSON zone data    |application/ubjson
|DGGS-JSON-FG zone data   |application/geo+json (with `profile` query parameter values of `jsonfg-dggs`, `jsonfg-dggs-plus`, `jsonfg-dggs-zoneids` or `jsonfg-dggs-zoneids-plus`)
|DGGS-UBJSON-FG zone data |application/geo+ubjson (with `profile` query parameter values of `jsonfg-dggs`, `jsonfg-dggs-plus`, `jsonfg-dggs-zoneids` or `jsonfg-dggs-zoneids-plus`)
|GeoJSON / JSON-FG data   |application/geo+json (without `profile` query parameter, or with values of `rfc7946`, `jsonfg` or `jsonfg-plus`)
|GeoTIFF data             |image/tiff; application=geotiff
|netCDF zone data         |application/netcdf (rasterized to sub-zones for `profile` query parameter values of `netcdf3-dggs`, `netcdf3-dggs-zoneids`, `netcdf4-dggs`, `netcdf4-dggs-zoneids` )
|Zarr zone data           |application/zarr+zip (rasterized to sub-zones for `profile` query parameter values of `zarr2-dggs` or `zarr2-dggs-zoneids`)
|CoverageJSON zone data   |application/prs.coverage+json (rasterized to sub-zones for `profile` query parameter values of `covjson-dggs` or `covjson-dggs-zoneids`)
|PNG zone data            |image/png
|JPEG XL zone data        |image/jxl
|====

[[rc_data-json]]
=== Requirements Class "DGGS-JSON Zone data encoding" (for data rasterized to sub-zones)

==== Overview

The DGGS-JSON Zone Data encoding requirements class defines support for encoding a DGGS Zone data response in JSON, using a schema defined below named "DGGS-JSON".

This encoding is intended to support one-to-one mapping of sub-zones values, for one or more zone depths, regardless of zone geometry type, in a human-readable format.

Values are encoded as a one-dimensional array following a sub-zone order defined by the DGGRS.

Example encodings follow:

.Example encoding for DGGS-JSON
[source,json]
----
include::../examples/1-temperature.json[]
----

.A more complex example encoding for DGGS-JSON with more variables and additional dimensions beyond those of the DGGRS
[source,json]
----
include::../examples/2-multidimensions-variables.json[]
----

include::../requirements/requirements_class_zone_data_json.adoc[]

IMPORTANT: For DGGS-JSON containing additional dimensions, the one-dimensional array of `values` is ordered in a _sub-zone order major_ manner. This is so all values of a particular field for a given sub-zone are
regrouped together. Values for the first dimensions listed in the `dimensions` array are then regrouped together, followed by additional dimensions as they appear in order in the dimensions array.

[[rc_data-ubjson]]
=== Requirements Class "DGGS-UBJSON Zone data encoding" (for data rasterized to sub-zones)

==== Overview

The DGGS-UBJSON Zone Data encoding requirements class defines support for encoding a DGGS Zone data response using the same JSON structure as the above JSON data requirements class but using the binary https://ubjson.org[UBJSON] encoding.

include::../requirements/requirements_class_zone_data_ubjson.adoc[]

TIP: The https://pypi.org/project/py-ubjson/[py-ubjson] tool can be used to easily convert between JSON and UBJSON.
After installing with `pip3 install py-ubjson`, a DGGS-JSON file can be converted to DGGS-UBJSON with
`ubjson fromjson zoneData.dggs.json`, and a DGGS-UBJSON file can be converted to DGGS-JSON with `ubjson tojson zoneData.dggs.ubj`.

[[rc_data-dggs-jsonfg]]
=== Requirements Class "DGGS-JSON-FG Zone data encoding" (for geometry coordinates quantized to sub-zones)

==== Overview

The DGGS-JSON-FG Zone Data encoding requirements class defines support for encoding a DGGS Zone data response for vector features in JSON.
This is accomplished by extending https://docs.ogc.org/DRAFTS/21-045r1.html[OGC Features & Geometry JSON]
with the concepts of DGGRS, reference parent zone, relative depth and deterministic sub-zone order, allowing to encode coordinates pairs as local sub-zone indices.
Alternatively, coordinates can be encoded using global zone IDs.

DGGS-JSON-FG Zone Data is intended to support efficient encoding of vector geometry at arbitrary precision using finer grids to locally address the inside of the reference parent zones.
This is done in a manner agnostic of the DGGRS (which needs to define a deterministic sub-zone order), in a human-readable format sharing as much as possible with existing practice for exchanging
geospatial vector data in JSON.

An Implementation may support a DGGS-FG-JSON representation where DGGS-quantized coordinates are specified either as global zone identifiers or as local indices into the deterministic zone order,
and may also support GeoJSON / JSON-FG compatibility modes where coordinates are additionally specified as positions on spatiotemporal axes for interoperability with non-DGGS clients.

A `profile` query parameter can be used by clients to request a particular DGGS-JSON-FG representation from Implementations supporting multiple options:

- `jsonfg-dggs`: DGGS-JSON-FG with `dggsPlace` coordinates corresponding to local sub-zone indices
- `jsonfg-dggs-plus`: DGGS-JSON-FG with `dggsPlace` coordinates corresponding to local sub-zone indices, in addition to GeoJSON (`geometry`) and/or JSON-FG compatibility mode (`place`)
- `jsonfg-dggs-zoneids`: DGGS-JSON-FG with `dggsPlace` coordinates corresponding to global textual identifiers
- `jsonfg-dggs-zoneids-plus`: DGGS-JSON-FG with `dggsPlace` coordinates corresponding to global textual identifiers, in addition to GeoJSON (`geometry`) and/or JSON-FG compatibility mode (`place`)

Example encodings follow:

.Example encoding of DGGS-JSON-FG for OpenStreetMap data
[source,json]
----
include::../examples/3-osmOttawa-extract.dggsjsonfg[]
----

.Example encoding of DGGS-JSON-FG for Natural Earth bathymetry in the arctic
[source,json]
----
include::../examples/4-arcticBathymetry-extract.dggsjsonfg[]
----

include::../requirements/requirements_class_zone_data_dggs_jsonfg.adoc[]

[[rc_data-dggs-ubjsonfg]]
=== Requirements Class "DGGS-UBJSON-FG Zone data encoding" (for geometry coordinates quantized to sub-zones)

==== Overview

The DGGS-UBJSON-FG Zone Data encoding requirements class defines support for encoding a DGGS Zone data response for vector features using the same JSON structure as the above DGGS-JSON-FG data requirements class,
but using the binary UBJSON encoding.

include::../requirements/requirements_class_zone_data_dggs_ubjsonfg.adoc[]

TIP: The https://pypi.org/project/py-ubjson/[py-ubjson] tool can be used to easily convert between JSON and UBJSON.
After installing with `pip3 install py-ubjson`, a DGGS-JSON-FG file can be converted to DGGS-UBJSON-FG with
`ubjson fromjson zoneData.dggsjsonfg`, and a DGGS-UBJSON-FG file can be converted to DGGS-JSON-FG with `ubjson tojson zoneData.dggsfg.ubj`.

[[rc_data-geotiff]]
=== Requirements Class "GeoTIFF Zone data encoding"

==== Overview

The GeoTIFF Zone Data encoding requirements class defines support for encoding a DGGS Zone data response according to the https://docs.ogc.org/is/19-008r4/19-008r4.html[OGC GeoTIFF standard].

GeoTIFF is a commonly used format for representing 2-dimensional gridded coverages.

For a DGGRS with non-rectangular zones (e.g., hexagonal zones), a GeoTIFF representation can be the minimal bounding rectangle of the zone shape, with NODATA values used outside the bounds of the zone.

include::../requirements/requirements_class_zone_data_geotiff.adoc[]

[[rc_data-geojson]]
=== Requirements Class "GeoJSON Zone data encoding"

==== Overview

The GeoJSON Zone Data encoding requirements class defines support for encoding a DGGS Zone data response according to the https://datatracker.ietf.org/doc/html/rfc7946[GeoJSON specification],
and optionally according to the https://docs.ogc.org/DRAFTS/21-045.html[OGC JSON-FG candidate Standard].

GeoJSON is a commonly used format for representing features with simple geometries and related properties.
GeoJSON is simple to understand and is well supported by tools and software libraries.
Since most Web developers are comfortable with using JSON-based formats, supporting GeoJSON is recommended for a vector representation of DGGS Zone data.

JSON-FG is an OGC format for representing features with simple geometries and related properties extending GeoJSON for greater flexibility.

An Implementation may support JSON-FG representations in addition to GeoJSON as defined by RFC 7946.

A `profile` query parameter can be used by clients to request a particular GeoJSON / JSON-FG representation from Implementations supporting multiple options:

- `rfc7946`: GeoJSON as defined by RFC 7946
- `jsonfg`: GeoJSON as extended by JSON-FG
- `jsonfg-plus`: JSON-FG extensions in addition to GeoJSON compatibility
(geometry specified in `geometry` limited to GeoJSON types, with coordinates either in `OGC:CRS84` or in a CRS explicitly requested by the client using `crs` query parameter)

include::../requirements/requirements_class_zone_data_geojson.adoc[]

[[rc_data-netcdf]]
=== Requirements Class "netCDF zone data encoding"

==== Overview

The netCDF Zone Data encoding requirements class defines support for encoding a DGGS Zone data response according to the https://portal.ogc.org/files/?artifact_id=43732[OGC netCDF standard] and
to any encoding extension such as the https://portal.ogc.org/files/?artifact_id=43734[NetCDF classic and 64-bit offset format], or netCDF version 4 based on https://docs.ogc.org/is/18-043r3/18-043r3.html[OGC HDF5].
NetCDF (network Common Data Form) is a data model for array-oriented scientific data, a freely distributed collection of access libraries implementing support for that data model, and
machine-independent formats.

An Implementation may support either a DGGS-optimized netCDF representation where a dimension is associated with sub-zones, with coordinates being global zone identifiers or local indices into the deterministic
zone order, or a traditional representation interoperable with non-DGGS clients where spatiotemporal axes are individual dimensions.

A `profile` query parameter can be used by clients to request a particular netCDF representation from Implementations supporting multiple options:

- `netcdf3`: NetCDF classic and 64-bit offset format (not quantized to DGGH)
- `netcdf3-dggs`: NetCDF classic and 64-bit offset format where one axis corresponds to local sub-zone indices
- `netcdf3-dggs-zoneids`: NetCDF classic and 64-bit offset format where one axis corresponds to the global identifiers of sub-zones (textual or 64-bit integer)
- `netcdf4`: HFG5-based NetCDF 4 format (not quantized to DGGH)
- `netcdf4-dggs`: HDF5-based NetCDF 4 format where one axis corresponds to local sub-zone indices
- `netcdf4-dggs-zoneids`: HDF5-based NetCDF 4 format where one axis corresponds to the global identifiers of sub-zones (textual or 64-bit integer)

include::../requirements/requirements_class_zone_data_netcdf.adoc[]

[[rc_data-zarr]]
=== Requirements Class "Zarr zone data encoding"

==== Overview

The Zarr Zone Data encoding requirements class defines support for encoding a DGGS Zone data response according to the https://www.opengis.net/doc/CS/zarr/2.0[OGC Zarr Storage Specification 2.0 Community Standard], packed into a <<ZIPISO,Zip archive>>.

An Implementation may support either a DGGS-optimized Zarr representation where a dimension is associated with sub-zones, with coordinates being global zone identifiers or local indices into the deterministic
zone order, or a traditional representation interoperable with non-DGGS clients where spatiotemporal axes are individual dimensions.

A `profile` query parameter can be used by clients to request a particular Zarr representation from Implementations supporting multiple options:

- `zarr2`: Zipped Zarr 2.0 (not quantized to DGGH)
- `zarr2-dggs`: Zipped Zarr 2.0 where one axis corresponds to local sub-zone indices
- `zarr2-dggs-zoneids`: Zipped Zarr 2.0 where one axis corresponds to the global identifiers of sub-zones (textual or 64-bit integer)

include::../requirements/requirements_class_zone_data_zarr.adoc[]

[[rc_data-coveragejson]]
=== Requirements Class "CoverageJSON zone data encoding"

==== Overview

The CoverageJSON requirements class defines support for encoding a DGGS Zone data response according to the https://docs.ogc.org/cs/21-069r2/21-069r2.html[OGC CoverageJSON Community Standard].

An Implementation may support either a DGGS-optimized CoverageJSON representation where a dimension is associated with sub-zones, with coordinates being global zone identifiers or local indices into the deterministic
zone order, or a traditional representation interoperable with non-DGGS clients where spatiotemporal axes are individual dimensions.

A `profile` query parameter can be used by clients to request a particular CoverageJSON representation from Implementations supporting multiple options:

- `covjson`: CoverageJSON (not quantized to DGGH)
- `covjson-dggs`: CoverageJSON where one axis corresponds to local sub-zone indices
- `covjson-dggs-zoneids`: CoverageJSON where one axis corresponds to the global identifiers of sub-zones (textual or 64-bit integer)

include::../requirements/requirements_class_zone_data_coveragejson.adoc[]

[[rc_data-jpegxl]]
=== Requirements Class "JPEG-XL Zone data encoding"

==== Overview

The JPEG XL Zone Data encoding requirements class defines support for encoding a DGGS Zone data response according to the https://jpeg.org/jpegxl/[JPEG XL] https://www.iso.org/standard/77977.html[ISO/IEC 18181 Standard].

JPEG XL supports a large number of bands, image dimensions, and floating point values.

include::../requirements/requirements_class_zone_data_jpegxl.adoc[]

[[rc_data-png]]
=== Requirements Class "PNG Zone data encoding"

==== Overview

The PNG Zone Data encoding requirements class defines support for encoding a DGGS Zone data response according to the https://www.w3.org/TR/2003/REC-PNG-20031110/[W3C Portable Network Graphics (PNG) Specification] (https://www.iso.org/standard/29581.html[ISO/IEC 15948:2003]).

Because PNG encoding is limited to an integer data values, this requirements class defines additional parameters and response headers allowing a client to request
a specific scale factor and offset to be used to quantize data values, and allowing the implementation to inform the client of the scale factor and offset
used for that quantization.

include::../requirements/requirements_class_zone_data_png.adoc[]
