== Terms and definitions

[[term-child-zone]]
=== child zone

immediate descendant of a <<term-parent-zone,parent zone>>

[.source]
<<OGC20-040r3>>

NOTE: adapted from _child cell_ in OGC Abstract Specification Topic 21

[[term-dgg]]
=== discrete global grid (DGG)

set of <<term-zone,zones>> at the same <<term-refinement-level,refinement level>>, that uniquely and completely cover a <<term-globe,globe>>

[.source]
<<OGC20-040r3>>

NOTE: Adapted to use `zones` rather than `cells` to avoid potential confusion with the similar concept of grid cells in a https://portal.ogc.org/files/?artifact_id=19820[_coverage_].
As noted in OGC Abstract Specification Topic 21, _"While the terms cell and zone are often used interchangeably, strictly zone is the preferred term."_.

[[term-dggh]]
=== discrete global grid hierarchy (DGGH)

series of <<term-dgg,discrete global grids>> organized in a hierarchy of successive <<term-refinement-level,levels of zone refinement>>, using a specific set of parameters fully establishing the geometry of all <<term-zone,zones>>

[.source]
<<OGC20-040r3>>

NOTE: Example of parameters part of the DGGH definition include the underlying Earth model spheroid, and the orientation of a base polyhedron.

NOTE: This definition corresponds to the term https://docs.ogc.org/as/20-040r3/20-040r3.html#hierarchy["hierarchy" (4.26)] in OGC Abstract Specification Topic 21,
and refers strictly to a mathematical structure, excluding the concept of <<term-zoneid,zonal identifiers>>, which are introduced as part of a <<term-dggrs,discrete global grid reference system>>, and
excluding notions of software functionality or interoperability implied by a <<term-dggs,DGGS>>.

NOTE: In some DGGS literature, the term DGGS refers to this DGGH meaning, where the word _system_ in "system of discrete global grids" is used in the sense of a "series" of grids
(e.g., _"A Discrete Global Grid System (DGGS) is a series of discrete global grids"_ [<<Sahr2003>>]), as opposed to a software or data integration / processing system.

NOTE: The ISEA3H (Icosahedral Snyder Equal-Area Aperture 3 Hexagonal) Discrete Global Grid Hierarchy, using the standard ISEA orientation and the WGS84 authalic sphere as the underlying Earth model,
irrespective of a particular indexing scheme or sub-zone ordering, is an example of a DGGH.

[[term-dggrs]]
=== discrete global grid reference system (DGGRS)

integrated system comprised of a specific <<term-dggh,discrete global grid hierarchy>>, spatio-temporal referencing by <<term-zoneid,zone identifiers>> and deterministic <<term-sub-zone,sub-zone>> ordering

[.source]
<<OGC20-040r3>>

NOTE: the term DGGRS did not appear in the terms of definitions of version 2.0.0 of OGC Abstract Specification Topic 21, but is defined in Section 8 as the `DGG_ReferenceSystem` interface.

NOTE: <<annex-dggrs-def,Annex B>> provides an informative schema for defining a DGGRS with accompanying examples of specific DGGRSs.

NOTE: this standard introduces the concept of sub-zone ordering, which is not part of the `DGG_ReferenceSystem` interface defined in topic 21, for the purpose of compact storage and transmission
of data quantized to a particular DGGRS.

[[term-dggs]]
=== discrete global grid system (DGGS)

integrated system comprising a <<term-dggh,hierarchy of discrete global grids>>, spatio-temporal referencing by <<term-zoneid,zonal identifiers>> and functions for quantization, zonal query, and interoperability

[.source]
<<OGC20-040r3>>

NOTE: In some DGGS literature, the term DGGS is sometimes used with the meaning of a <<term-dggh,discrete global grid hierarchy>>.

NOTE: An implementation of OGC API - DGGS would be considered a DGGS.

[[term-globe]]
=== globe

region of space-time enclosing a celestial body

[.source]
<<OGC20-040r3>>

[[term-parent-zone]]
=== parent zone

<<term-zone,zone>> in a lower <<term-refinement-level,refinement level>> of a <<term-dgg,discrete global grid>> with immediate descendants

[.source]
<<OGC20-040r3>>

NOTE: adapted from _parent cell_ in OGC Abstract Specification Topic 21

NOTE: Adapted to say _lower_ rather than _higher_, where _lower_ refers to a zone covering a larger area of space-time which would normally correspond to lower resolution data.

[[term-refinement-level]]
=== refinement level
numerical order of a <<term-dgg,discrete global grid>> in the tessellation sequence

NOTE: The discrete global grid with the least number of <<term-zone,zones>> has a refinement level of 0.

[.source]
<<OGC20-040r3>>

[[term-relative-depth]]
=== relative depth
the number of <<term-refinement-level,refinement levels>> separating a finer <<term-dgg,discrete global grid>> from a coarser discrete global grid in a <<term-dggh,discrete global grid hierarchy>>

[[term-sub-zone]]
=== sub-zone

<<term-zone,zone>> at a greater <<term-refinement-level,refinement level>> than a <<term-parent-zone,parent zone>> whose geometry is at least partially contained within the geometry of the <<term-parent-zone,parent zone>>

NOTE: At a <<term-relative-depth,relative depth>> of 1, the sub-zones of the parent zone are its immediate <<term-child-zone,children>>.

NOTE: In some <<term-dggh,DGGHs>>, the children of the children of a parent zone (relative depth of 2) are not all sub-zones of that parent zone.

NOTE: A <<term-dggrs,discrete global grid reference system>> defines a deterministic order for sub-zones

[[term-web-api]]
=== Web API
An Application Programming Interface (API) using an architectural style that is founded on the technologies of the Web

[.source]
<<OGC19-072>>

NOTE: See https://www.w3.org/TR/dwbp/#accessAPIs[Best Practice 24: Use Web Standards as the foundation of APIs] (W3C Data on the Web Best Practices) for more detail.

[[term-zoneid]]
=== zone identifier

spatio-temporal reference in the form of a label or code that uniquely identifies a <<term-zone,zone>>

[.source]
<<OGC20-040r3>>

NOTE: synonym of "zonal identifier" and "zone ID".

NOTE: This standard and the DGGRS definitions described in <<annex-dggrs-def,Annex B>> require textual identifiers (which may or may not be comprised of only digit characters), while optionally supporting 64-bit integer identifiers for the purpose of compact transmission and internal representations.

[[term-zirs]]
=== zone identifier reference system (ZIRS)

reference system establishing a specific association of <<term-zoneid,zone identifiers>> to <<term-zone,zones>> for one or more <<term-dggh,discrete global grid hierarchy>>

NOTE: synonym of "zonal identifier reference system" and "zone indexing scheme"

[[term-zone]]
=== zone

particular region of space-time

[.source]
<<OGC20-040r3>>
