.Preface

This document defines the _OGC API - Discrete Global Grid Systems - Part 1: Core_ Standard. Suggested additions, changes and comments on this standard are welcome and encouraged.
Such suggestions may be submitted as an issue on the https://github.com/opengeospatial/ogcapi-dggs/issues[_OGC API - DGGS_ GitHub repository].

OGC API Standards define modular API components to spatially enable Web APIs in a consistent way. OGC API Standards use the OpenAPI specification for describing the API components.

The _OGC API - Discrete Global Grid Systems_ defines API components to retrieve data and query zones based on Discrete Global Grid Systems (DGGS) concepts defined in
https://docs.ogc.org/as/20-040r3/20-040r3.html[OGC Abstract Specification Topic 21].
Additional parts for the _OGC API - Discrete Global Grid Systems_ Standard may be defined in the future to provide additional capabilities.

////
*OGC Declaration*
////

////
Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.
////

////
NOTE: Uncomment ISO section if necessary

*ISO Declaration*

ISO (the International Organization for Standardization) is a worldwide federation of national standards bodies (ISO member bodies). The work of preparing International Standards is normally carried out through ISO technical committees. Each member body interested in a subject for which a technical committee has been established has the right to be represented on that committee. International organizations, governmental and non-governmental, in liaison with ISO, also take part in the work. ISO collaborates closely with the International Electrotechnical Commission (IEC) on all matters of electrotechnical standardization.

International Standards are drafted in accordance with the rules given in the ISO/IEC Directives, Part 2.

The main task of technical committees is to prepare International Standards. Draft International Standards adopted by the technical committees are circulated to the member bodies for voting. Publication as an International Standard requires approval by at least 75 % of the member bodies casting a vote.

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. ISO shall not be held responsible for identifying any or all such patent rights.
////

== Security considerations

OGC API — DGGS — Part 1 only defines HTTP GET operations. As such the security considerations are limited to those applicable to a "read only" service.
However, implementations of the OGC API - DGGS Standard will have to process resource paths and query parameters in a way that cannot be used by a client
to inject malicious queries that makes available unforeseen data or even force the server to perform unwanted or dangerous actions.
The following paragraphs enumerate some security considerations.

Due to the flexibility in querying DGGS zones, implementations of the _OGC API - DGGS_ Standard that are not optimized can easily encounter requests that take some time to resolve.
If several of these requests are processed simultaneously, the server can become slow or unresponsive.
Servers should take advantage of the space partitioning structures of the implemented Discrete Global Grid Reference Systems (DGGRSs) that guarantee a deterministic maximum amount of data to process,
ensuring that maximum refinement level is used for regions covering a larger area, and refusing requests which would otherwise be problematic for the server.
Servers should also set and apply reasonable limits (e.g., maximum number of zones to return, etc.) to prevent Denial of Service attacks.

Some deployments of the OGC API - DGGS Standard may assign different roles to different users that may result in accessing different collections or geographical areas for which data can be retrieved or zones can be queried.
The access control can be described in the OpenAPI definition as discussed in the OGC API - Common Standard (https://docs.ogc.org/is/19-072/19-072.html#rc_oas30-security).
Servers should take care that all resources in all representations and ways they can be requested (e.g., adding query parameters) are managed consistently.

Another security consideration is that DGGS data or DGGS zone lists returned by a DGGS API endpoint may be positionally incorrect and potentially guide users to wrong locations.
One possible way this situation could happen is the manipulation by a malicious actor of a projection library installed on a server deployment.

Using HTTPS queries is preferred to using HTTP. The obvious reason is the DGGS response returned by the DGGS API endpoint should be only accessible to the requesting user.
Another reason is related to the public accessibility of the request itself.
Request to a DGGS API endpoint reveal geographical extents that might be associated with private or sensitive information. For instance, users commonly visit "home" or "work" or "target places"
(such as holiday destinations or churches). These requests can be used to predict personal or private activities.

== Submitters

All questions regarding this submission should be directed to the editors or the submitters:


[%unnumbered]
|===
| *Name*                                  | *Affiliation*
| Matthew Brian John Purss (editor)       | Pangaea Innovations Pty. Ltd.
| Jérôme Jacovella-St-Louis (editor)      | Ecere Corporation
| Robert Gibb                             | Landcare Research New Zealand
| Fuhu Ren / 任伏虎                        | Peking University Collaborative Innovation Center for Geospatial Big Data
| Peter Strobl                            | European Commission Joint Research Centre
| Ryan Ahola                              | Natural Resources Canada
| Alexander Kmoch                         | University of Tartu
| Ferran Gascon                           | European Space Agency
| Luís Moreira de Sousa                   | Open Source Geospatial Foundation
| Perry Peterson                          | University of Calgary
| Michael Jendryke                        | GeoInsight AG
|===

[abstract]
== Abstract

The OGC API - Discrete Global Grid Systems - Part 1: Core Standard defines requirements that can be implemented and integrated into a deployed Web API.
The DGGS API allows to retrieve geospatial data for a specific area, time and resolution of interest, based on a specific DGGRS.
Additionally, the DGGS API defines operations to query the list of DGGRS zones from which data is available and/or matching a specified query.
Such queries are expressed by combining HTTP query parameters, including the possibility to express more complex filtering queries using the
http://www.opengis.net/doc/IS/cql2/1.0[OGC Common Query Language (CQL2)].

Readers are strongly encouraged to first familiarize themselves with the DGGS concepts defined in
https://docs.ogc.org/as/20-040r3/20-040r3.html[OGC Abstract Specification Topic 21] laying the foundation for this Standard.

Please note that in the remainder of this document, the Standard will be referred to as the "OGC API – DGGS Standard", "the DGGS API" or "this Standard".

[.preface]
== Acknowledgements

This OGC Standard builds on a vast amount of research on Discrete Global Grid Systems spanning multiple decades, in particular from John P. Snyder (<<Snyder1992>>), Michael F. Goodchild (<<Goodchild1992>>),
Kevin Sahr (<<Sahr2003>>), Robert Gibb (<<Gibb2016>>), Perry R. Peterson (<<Peterson2019>>), and several others.

Initial implementations of a previous iteration of a draft DGGS API and an Engineering Report produced thanks to funding from OGC Testbed 16 (<<OGC20-039r2>>) informed the development of this Standard.
Note that the API defined by this Standard differs significantly from that earlier iteration, with a greater emphasis on client requests asking a Web API implementation questions of the type _"What is here?"_ and _"Where is it"_? (<<Peterson2019>>).
This Standard assumes a shared understanding of a particular Discrete Global Grid Reference System between the client and the server, which could be implemented by a local DGGRS software library,
avoiding the need to define HTTP resources to query the conceptual grid hierarchy structure. The definition of an API in the traditional software development sense for such DGGRS libraries is beyond the scope of this Standard.

Key work leading to the creation of this OGC Standard was undertaken as part of GeoConnections 2020-2021 and 2025-2027 projects GNS20-21IFP02 (_Modular OGC API Workflows_) (<<OGC21-033>>) and GNS25-27IFP2
(Advancing and Implementing OGC Standards for GeoDataCubes, DGGSs, Data Stores for Digital Twins and Cartographic Symbology).
Financial support provided by GeoConnections, a national collaborative initiative led by Natural Resources Canada.
GeoConnections supports the modernization of the Canadian Geospatial Data Infrastructure (CGDI). The CGDI is the collection of geospatial data, standards, policies, applications, and governance that facilitate its access, use, integration, and preservation.
Research activity and Technology Integration Experiments performed as part of the OGC Federated Marine SDI - Phase 3 (<<OGC23-010>>) pilot project also played
a key role in refining the design of the API and the Discrete Global Grid Reference Systems based on the ISEA projection included in <<annex-dggrs-def>>.
