[[rc_zone-query]]
== Requirements Class "Zone Query"

=== Overview

The OGC API - DGGS "Zone Query" requirements class supports requesting the list of zones from a specific
DGGRS, that is a specific hierarchy of Discrete Global Grids
combined with a particular ZIRS, for which there is
data available, or matching a particular query (e.g., using a filtering query parameter).
This requirements class describes an HTTP GET operation, as well as its response.
The selected DGGRS is listed as available and described in the <<rc_core,Core requirements class>>,
and conforms to https://www.opengis.net/doc/AS/dggs/2.0[OGC Topic 21].
The list of zones from a Web API using this requirements class can either be
for a particular collection of geospatial data, for a dataset as a whole, or
in connection with https://docs.ogc.org/DRAFTS/21-009.html[_OGC API - Processes - Part 3: Workflows & Chaining_], the output of
a processing workflow.

This requirements class enables a client to ask a question of the type _**"Where is it?"**_. The _"where"_
refers to the spatiotemporal response encoded as a list of Zone IDs. The _it_ refers to either
the availability of data associated with a particular collection, dataset, or processing workflow
(where the result itself could simply be this spatiotemporal region),
as well as the evaluation of any additional filtering query expressed as per the <<rc_zone-query-cql2-filter, CQL2 filtering requirements class>>.

Implementations of this requirements class are required to support at minimum the JSON encoding of zones list.
This encoding provides an easy to implement, reasonably efficient and interoperable mechanism to exchange lists of zone identifiers.
The JSON response consists of a simple object with a `"zones"` array property listing the zone identifiers as strings.
The object can also include a `"links"` objects linking back to other resources of the DGGRS.

By default, zones are returned as a compacted list of zones, which recursively replaces children zones by their parent if all children of the parent are included in the response.
A client can override this default behavior by setting the `compact-zones` query parameter to _false_.

include::../requirements/requirements_class_zone-query.adoc[]
