== Conformance
The one Standardization Target for this standard is Web APIs.

_OGC API - Common_ provides a common foundation for OGC API Standards.
Some conformance classes of this standard have a dependency on, or are designed to be easily integrated with, conformance classes defined in https://docs.ogc.org/is/19-072/19-072.html[OGC API - Common - Part 1] and/or https://docs.ogc.org/DRAFTS/20-024.html[_Part 2_],
as well as within a Web API conforming to additional OGC API Standards.

This standard identifies twenty one Conformance Classes. Each Conformance Class has an associated Requirements Class.
The Requirements Classes define the functional requirements which will be tested through the associated Conformance Class.
Only the Core requirements class is mandatory, all others are optional.
However, a Web API with practical use needs to implement either the Data Retrieval and/or the Zone Query requirement class.

Conformance with this standard shall be checked using all the relevant tests specified in Annex A (normative) of this document.
The framework, concepts, and methodology for testing, and the criteria to be achieved to claim conformance are specified in the OGC Compliance Testing Policies and Procedures and the OGC Compliance Testing web site.

In order to conform to this OGC® interface standard, a software implementation shall implement at minimum the "Core" requirements class, as well as either
the "Data Retrieval" and/or the "Zone Query" requirements class, defined in Annex A (normative).

All requirements-classes and conformance-classes described in this document are owned by the standard(s) identified.

The Requirements Classes for _OGC API - Discrete Global Grid Systems_ are:

=== Requirements classes defining resources

In addition to the Core requirement class defining the `../dggs`, `../dggs/{dggrsId}` and `../dggs/{dggrsId}/zones/{zoneId}` resources, either
the Zone Data retrieval (`../dggs/{dggrsId}/zones/{zoneId}/data`) or Zone Query requirement classes (`../dggs/{dggrsId}/zones` with support for parameters such as
`zone-level=`, `parent-zone=`, `compact-zones=`, `bbox=` and `datetime=`) need to be implemented for a DGGS API implementation to have practical use.

* <<rc_core,*Core*>>
* <<rc_data-retrieval,*Zone Data Retrieval*>>
* <<rc_zone-query,*Zone Query*>>

=== Requirements classes defining origins

These requirement classes define DGGS resources for the API (`/dggs`) and collections (`/collections/{collectionId}/dggs`).

* <<rc_root-dggs,*Root DGGS*>>
* <<rc_collection-dggs,*Collection DGGS*>>

=== Requirements classes defining parameters

Two requirement classes adds support for the `subset` and `zone-depth` parameters to zone data resources:

* <<rc_data-subsetting,*Zone data subsetting*>>
* <<rc_data-custom-depths,*Zone data custom depths*>>

A requirement classes adds support for the `filter` parameter for zone query resources:

* <<rc_cql2-query,*Filtering Zone Queries with CQL2*>>

=== Requirements classes defining resource representations

==== Zone data encodings

The Data Encoding Requirements Classes address support for formats commonly used for encoding geospatial data, as well as encodings
based on JSON and UB-JSON using a schema scpecifically designed for the purpose of encoding one or more depths of zone data referenced to a DGGS,
including optional support for multiple fields (properties) and additional dimensions beyond those of the DGGS.

* <<rc_data-json,DGGS-JSON Data>>
* <<rc_data-ubjson,DGGS-UB-JSON Data>>
* <<rc_data-geojson,GeoJSON Data>>
* <<rc_data-fgjson,FG-JSON Data>>
* <<rc_data-geotiff,GeoTIFF Data>>
* <<rc_data-netcdf,netCDF Data>>
* <<rc_data-coveragejson,CoverageJSON Data>>
* <<rc_data-jpegxl,JPEG XL Data>>
* <<rc_data-png,PNG Data>>

==== Zone list encodings

The Zone List Encoding Requirements Classes address support for formats efficiently and/or intuitively encoding a list of DGGS zone identifiers.

* <<rc_zone-json,JSON Zone List>>
* <<rc_zone-html,HTML Zone List>>
* <<rc_zone-binary64bit,64-bit Binary Zone List>>
* <<rc_zone-geojson,GeoJSON Zone List>>
* <<rc_zone-fgjson,FG-JSON Zone List>>
* <<rc_zone-geotiff,GeoTIFF Zone List>>

==== Operation IDs in API definitions

The _Operation IDs_ Requirements Class defines requirements for using specific operation IDs in API definitions, which can be combined with requirement classes for specific API definition,
such as the OpenAPI 3.0 requirement class of _OGC API - Common - Part 1: Core_, facilitating the identification of DGGS resources.

* <<rc_operation-ids,*Operation IDs*>>

=== Summary of conformance URIs

[#table_conformance_urls,reftext='{table-caption} {counter:table-num}']
.Conformance class URIs
[cols="30,70",options="header"]
|===
| Corresponding requirements class               | Conformance class URI
| <<rc_core,Core>>                               | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/core
| <<rc_data-retrieval,Zone Data Retrieval>>      | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-retrieval
| <<rc_zone-query,Zone Query>>                   | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-query
| <<rc_cql2-query,Filtering Zone Queries with CQL2>> | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/cql2-query
| <<rc_root-dggs,Root DGGS>>                     | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/root-dggs
| <<rc_collection-dggs,Collection DGGS>>         | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/collection-dggs
| <<rc_data-subsetting,Data subsetting>>         | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-subsetting
| <<rc_data-custom-depths,Data custom depths>>   | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-custom-depths
| <<rc_data-geojson,DGGS-JSON Data>>             | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-json
| <<rc_data-ubjson,DGGS-UB-JSON Data>>           | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-ubjson
| <<rc_data-geojson,GeoJSON Data>>               | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-geojson
| <<rc_data-fgjson,FG-JSON Data>>                | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-fgjson
| <<rc_data-geotiff,GeoTIFF Data>>               | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-tiff
| <<rc_data-netcdf,netCDF Data>>                 | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-netcdf
| <<rc_data-coveragejson,CoverageJSON Data>>     | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-coveragejson
| <<rc_data-jpegxl,JPEG XL Data>>                | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-jpegxl
| <<rc_data-png,PNG Data>>                       | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-png
| <<rc_zone-geojson,JSON Zone List>>             | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-json
| <<rc_zone-html,HTML Zone List>>                | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-html
| <<rc_zone-geotiff,64-bit Binary Zone List>>    | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-uint64
| <<rc_zone-geojson,GeoJSON Zone List>>          | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-geojson
| <<rc_zone-fgjson,FG-JSON Zone List>>           | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-fgjson
| <<rc_zone-geotiff,GeoTIFF Zone List>>          | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-tiff
| <<rc_operation-ids,Operation IDs>>             | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/operation-ids
|===
