== DGGS - Data Retrieval Conformance Classes

=== Requirement Class DGGS - Data Retrieval

The Data Retrieval conformance class allows to retrieve data from a specific
Discrete Global Grid System (DGGS) in a particular indexing scheme from either an individual
zone, or a list of zones referenced by ID.
It describes an HTTP GET operation, as well as its response.
The selected DGGS is listed as available and described in the Core conformance class,
and conforms to OGC Topic 21.
The conformance makes use of URI templates for a variable representing the Zone ID.
The data retrieved from a Web API using this conformance class can either be
for a particular collection of geospatial data, for a dataset as a whole, or
in connection with _OGC API - Processes - Part 3: Workflows & Chaining_, the output of
a processing workflow.

include::../requirements/requirements_class_data-retrieval.adoc[]

==== Retrieve data from single zone

The following requirements describe how a client can retrieve data from a single DGGS zone
at the resource path `.../dggs/{dggsId}/zones/{zoneId}/data`.

===== Operation

include::../requirements/data-retrieval/REQ_data-retrieval_single-zone-data-op.adoc[]

===== Response

include::../requirements/data-retrieval/REQ_data-retrieval_single-zone-data-response.adoc[]

=== Requirement Class DGGS - Multi-Zone Data Retrieval

The Multi-Zone Data Retrieval conformance class allows to retrieve data from a specific
Discrete Global Grid System (DGGS) in a particular indexing scheme from a list of zones
referenced by ID.
It describes an HTTP GET operation, as well as its response.
The selected DGGS is listed as available and described in the Core conformance class,
and conforms to OGC Topic 21.
The conformance makes use of URI templates for a variable representing the Zone ID.
The data retrieved from a Web API using this conformance class can either be
for a particular collection of geospatial data, for a dataset as a whole, or
in connection with _OGC API - Processes - Part 3: Workflows & Chaining_, the output of
a processing workflow.

include::../requirements/requirements_class_multi-zone-data-retrieval.adoc[]

==== Retrieve data from multiple zones

The following requirements describe how a client can retrieve data from a single DGGS zone
at the resource path `.../dggs/{dggsId}/data?zones={zoneId},...`.

===== Operation

include::../requirements/multi-zone-data-retrieval/REQ_data-retrieval_multi-zone-data-op.adoc[]

===== Response

include::../requirements/multi-zone-data-retrieval/REQ_data-retrieval_multi-zone-data-response.adoc[]
