.Preface

[NOTE]
====
OGC API standards define modular API building blocks to spatially enable Web APIs in a consistent way. The OpenAPI specification is used to define the API building blocks.

_OGC API - Discrete Global Grid Systems_ provides API building blocks to retrieve data and query zones based on Discrete Global Grid Systems (DGGS) concepts defined in
https://docs.ogc.org/as/20-040r3/20-040r3.html[OGC Abstract Topic 21].
Additional parts for _OGC API - Discrete Global Grid Systems_ may be defined in the future to provide additional capabilities.

====

////
*OGC Declaration*
////

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.

////
NOTE: Uncomment ISO section if necessary

*ISO Declaration*

ISO (the International Organization for Standardization) is a worldwide federation of national standards bodies (ISO member bodies). The work of preparing International Standards is normally carried out through ISO technical committees. Each member body interested in a subject for which a technical committee has been established has the right to be represented on that committee. International organizations, governmental and non-governmental, in liaison with ISO, also take part in the work. ISO collaborates closely with the International Electrotechnical Commission (IEC) on all matters of electrotechnical standardization.

International Standards are drafted in accordance with the rules given in the ISO/IEC Directives, Part 2.

The main task of technical committees is to prepare International Standards. Draft International Standards adopted by the technical committees are circulated to the member bodies for voting. Publication as an International Standard requires approval by at least 75 % of the member bodies casting a vote.

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. ISO shall not be held responsible for identifying any or all such patent rights.
////

[abstract]
== Abstract

This specification defines building blocks which can be used as part of a Web API to retrieve geospatial data for a specific
area, time and resolution of interest, based on a specific Discrete Global Grid System (DGGS) and indexing scheme,
as defined in https://docs.ogc.org/as/20-040r3/20-040r3.html[OGC Abstract Topic 21], as well to query the list of DGGS zones from which data is available and/or
matching a specify query (in combination with other building blocks defining queries, such as a filter defined using
the https://docs.ogc.org/DRAFTS/21-065.html[OGC Common Query Language (CQL2)].

== Submitters

All questions regarding this submission should be directed to the editors or the submitters:

[%unnumbered]
|===
| *Name*                                  | *Affiliation*
| Matthew Brian John Purss (editor)       | Pangaea Innovations Pty. Ltd.
| Jérôme Jacovella-St-Louis (editor)      | Ecere Corporation
|===
