[[zone-list-encodings-section]]
== Requirements Classes for Encodings of Zone list

This standard does not mandate any particular encoding or format in which to return the `../dggs/{dggrsId}/zones` resources.
DGGS Zone Lists can be encoded in any suitable data format.
However, it does define requirements class for zone list encodings which are expected to be commonly supported in implementations of this standard.
These requirements classes include:

* <<rc_zone-json,JSON Zone List>>
* <<rc_zone-binary64bit,64-bit Binary Zone List>>
* <<rc_zone-html,HTML Zone List>>
* <<rc_zone-geojson,GeoJSON Zone List>>
* <<rc_zone-fgjson,FG-JSON Zone List>>
* <<rc_zone-geotiff,GeoTIFF Zone List>>

[[zone_list_media_types]]
=== Media Types (for zone list)

A table of the media types used in the zone list encoding requirements classes defined in this standard follows.

[#api-dggs-zone-list-media-types,reftext='{table-caption} {counter:table-num}']
.Media Types used for zone list encoding requirements classes
[width="90%",cols="2,4"]
|====
^|*Encoding*              ^|*media type*
|GeoTIFF zone list         |image/tiff; application=geotiff
|GeoJSON zone list         |application/geo+json
|JSON-FG zone list         |application/fg+json
|JSON zone list            |application/json
|HTML zone list            |text/html
|Binary 64-bit zone list   |application/x-binary
|====

[[rc_zone-json]]
=== Requirements Class "JSON zone list encoding"

==== Overview

The JSON zone list encoding requirements class defines the ability to retrieve a JSON response for the DGGS zone list resource.

The response consists of a simple JSON object with a `"zones"` array property listing the zone identifiers as strings.
The object can also include a `"links"` objects linking back to other resources of the DGGS.

This requirement class provides an easy to implement, reasonably efficient and interoperable mechanism to exchange lists of zone identifiers.

include::../requirements/requirements_class_zone_list_json.adoc[]

[[rc_zone-html]]
=== Requirements Class "HTML zone list encoding"

==== Overview

The HTML zone list encoding requirements class defines at a high level the ability to retrieve an HTML response for the DGGS zone list resource intended primarily for users accessing the API from a Web browser.

The exact content of the HTML response is not prescribed, leaving the flexibility for implementations to choose a preferred approach.

HTML is the core language of the World Wide Web. An API that supports HTML will support browsing the spatial resources with a web browser and will also enable search engines to crawl and index those resources.

include::../requirements/requirements_class_zone_list_html.adoc[]

[[rc_zone-binary64bit]]
=== Requirements Class "Binary 64-bit integer zone list encoding"

==== Overview

The binary 64-bit integer zone list encoding requirements class defines the ability to retrieve a binary response for the DGGS zone list resource for
DGGRS whose zone identifiers can be expressed as a single 64-bit integer.

The response consists of a 64-bit integer count of zones, followed by that count of zones, also 64-bit integers.
With compact zones and additional HTTP content encoding compression, this provides an optimal way to exchange DGGS zone lists.

include::../requirements/requirements_class_zone_list_binary_64bit.adoc[]

[[rc_zone-geojson]]
=== Requirements Class "GeoJSON zone list encoding"

==== Overview

The GeoJSON zone list encoding requirements class defines support for encoding a DGGS Zone list response according to the https://datatracker.ietf.org/doc/html/rfc7946[GeoJSON specification].

The response is a feature collection where each feature represents a zone in the list.
The geometry of the zone shold be polygons or multipolygons (e.g., in the case of zone geometry which must be split on the anti-meridian or pole).
The zone identifier is represented in the `id` field of each feature.

While not intended to efficiently exchange zone list, as the response carries the geometry of the zones which could easily be computed client-side which takes considerable bandwidth and is
not necessary for a DGGS client working natively with the same DGGRS, this requirement class provides an easy way to readily visualize the response in a variety of tools.
This requirements class is therefore intended for convenience, demonstration and educational purposes.

include::../requirements/requirements_class_zone_list_geojson.adoc[]

[[rc_zone-fgjson]]
=== Requirements Class "FG-JSON zone list encoding"

==== Overview

The FG-JSON zone list encoding requirements class defines support for encoding a DGGS Zone list response according to the https://docs.ogc.org/DRAFTS/21-045.html[FG-JSON specification].

The response is a feature collection where each feature represents a zone in the list.
The geometry of the zone shold be polygons or multipolygons (e.g., in the case of zone geometry which must be split on the anti-meridian or pole).
The zone identifier is represented in the `id` field of each feature.

While not intended to efficiently exchange zone list, as the response carries the geometry of the zones which could easily be computed client-side which takes considerable bandwidth and is
not necessary for a DGGS client working natively with the same DGGRS, this requirement class provides an easy way to readily visualize the response in a variety of tools.
This requirements class is therefore intended for convenience, demonstration and educational purposes.

include::../requirements/requirements_class_zone_list_fgjson.adoc[]

[[rc_zone-geotiff]]
=== Requirements Class "GeoTIFF zone list encoding"

==== Overview

The GeoTIFF zone list encoding requirements class defines support for encoding a DGGS Zone list response according to the https://docs.ogc.org/is/19-008r4/19-008r4.html[OGC GeoTIFF standard],
intended primarily for DGGS with rectangular zones.

The response is a 2D gridded coverage where each cell is a zone in the list, in the coordinate reference system of that DGGS.

For DGGS with non-rectangular zones, the resolution would need to be higher than a single pixel per the most detailed zone to be returned in order to be able to recognize the zone geometry,
and would therefore be very sub-optimal. While for rectangular zones it would be easy to identify zones with a one-to-one correspondence, recognizing non-rectangular zones would be significantly more difficult.

While not intended to efficiently exchange zone list, this requirement class provides an easy way to readily visualize the response in a variety of tools.
This requirements class is therefore intended for convenience, demonstration and educational purposes.

include::../requirements/requirements_class_zone_list_geotiff.adoc[]
