== Conformance
The one Standardization Target for this Standard is Web APIs.

_OGC API - Common_ provides a common foundation for OGC API Standards.
Some conformance classes of this standard have a dependency on, or are designed to be easily integrated with, conformance classes defined in https://docs.ogc.org/is/19-072/19-072.html[OGC API - Common - Part 1] and/or https://docs.ogc.org/DRAFTS/20-024.html[_Part 2_],
as well as within a Web API conforming to additional OGC API Standards.

This Standard identifies twenty-five Conformance Classes. Each Conformance Class has an associated Requirements Class.
The Requirements Classes define the functional requirements which will be tested through the associated Conformance Class.
Only the Core requirements class is mandatory, all others are optional.
However, a Web API with practical use needs to implement either the Data Retrieval and/or the Zone Query requirements class.

Conformance with this Standard shall be checked using all the relevant tests specified in Annex A (normative) of this document.
The framework, concepts, and methodology for testing, and the criteria to be achieved to claim conformance are specified in the OGC Compliance Testing Policies and Procedures and the OGC Compliance Testing web site.

To conform to this OGC API - DGGS Standard, a software implementation shall implement at minimum the "Core" requirements class, as well as either
the "Data Retrieval" and/or the "Zone Query" requirements class.

All requirements-classes and conformance-classes described in this document are owned by the standard(s) identified.

The Requirements Classes for _OGC API - Discrete Global Grid Systems_ are:

=== Requirements classes defining resources

In addition to the Core requirements class defining the `../dggs`, `../dggs/{dggrsId}` and `../dggs/{dggrsId}/zones/{zoneId}` resources, either
the Zone Data retrieval (`../dggs/{dggrsId}/zones/{zoneId}/data`) or Zone Query requirements classes (`../dggs/{dggrsId}/zones` with support for parameters such as
`zone-level=`, `parent-zone=`, `compact-zones=`, `bbox=`, `bbox-crs`, `datetime=`, `subset=` and `subset-crs=`) need to be implemented for a DGGS API implementation to have practical use.

* <<rc_core,*Core*>>
* <<rc_data-retrieval,*Zone Data Retrieval*>>
* <<rc_zone-query,*Zone Query*>>

=== Requirements classes defining origins

These requirements classes define DGGS resources for the API (`/dggs`) and collections (`/collections/{collectionId}/dggs`).

* <<rc_root-dggs,*Root DGGS*>>
* <<rc_collection-dggs,*Collection DGGS*>>

=== Requirements classes defining parameters

Three requirements classes add support for the `subset`, `properties`, `exclude-properties`, `zone-depth` and `filter` parameters to zone data resources:

* <<rc_data-subsetting,*Zone data subsetting*>>
* <<rc_data-custom-depths,*Zone data custom depths*>>
* <<rc_data-cql2-filter,*Filtering zone data with CQL2*>>

A requirements class adds support for the `filter` parameter for zone query resources:

* <<rc_zone-query-cql2-filter,*Filtering Zone Queries with CQL2*>>

=== Requirements classes defining resource representations

==== Zone data encodings

The Data Encoding Requirements Classes address support for formats commonly used for encoding geospatial data, as well as encodings
based on JSON and https://ubjson.org/[UBJSON] using a schema specifically designed for zone data referenced to a particular DGGRS.
DGGS-(UB)JSON allows encoding one or more depths of DGGS-quantized raster data, including optional support for multiple fields (properties) and additional dimensions beyond those of the DGGS,
whereas DGGS-(UB)JSON-FG encode vector features and geometry based on OGC Features & Geometry JSON using sub-zone order indices as coordinates at an arbitrary relative depth / precision.

* <<rc_data-json,DGGS-JSON Data>>
* <<rc_data-ubjson,DGGS-UBJSON Data>>
* <<rc_data-dggs-jsonfg,DGGS-JSON-FG Data>>
* <<rc_data-dggs-ubjsonfg,DGGS-UBJSON-FG Data>>
* <<rc_data-geojson,GeoJSON Data>>
* <<rc_data-geotiff,GeoTIFF Data>>
* <<rc_data-netcdf,netCDF Data>>
* <<rc_data-zarr,Zarr Data>>
* <<rc_data-coveragejson,CoverageJSON Data>>
* <<rc_data-jpegxl,JPEG XL Data>>
* <<rc_data-png,PNG Data>>

==== Zone list encodings

The Zone List Encoding Requirements Classes address support for formats efficiently and/or intuitively encoding a list of DGGS zone identifiers, in addition to the simple JSON encoding.

* <<rc_zone-html,HTML Zone List>>
* <<rc_zone-uint64,64-bit Binary Zone List>>
* <<rc_zone-geojson,GeoJSON Zone List>>
* <<rc_zone-geotiff,GeoTIFF Zone List>>

Implementations supporting GeoJSON for either zone data or zone lists are strongly encouraged to also support GeoJSON extensions
defined by the Features & Geometry JSON (JSON-FG) Standard. Conformance to this Standard can be indicated in the Web API deployment's
conformance declaration using its associated conformance class URIs, such as `http://www.opengis.net/spec/json-fg-1/0.2/conf/core`.

==== Operation IDs in API definitions

The _Operation IDs_ Requirements Class defines requirements for using specific operation IDs in API definitions, which can be combined with requirements classes for specific API definition,
such as the OpenAPI 3.0 requirements class of _OGC API - Common - Part 1: Core_, facilitating the identification of DGGS resources.

* <<rc_operation-ids,*Operation IDs*>>

=== Summary of conformance URIs

[#table_conformance_urls,reftext='{table-caption} {counter:table-num}']
.Conformance class URIs
[cols="30,70",options="header"]
|===
| Corresponding requirements class               | Conformance class URI
| <<rc_core,*Core*>>                             | *https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/core*
2+| *_For Data Retrieval_*
| <<rc_data-retrieval,Zone Data Retrieval>>      | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-retrieval
| <<rc_data-subsetting,Data subsetting>>         | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-subsetting
| <<rc_data-custom-depths,Data custom depths>>   | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-custom-depths
| <<rc_data-cql2-filter,Filtering Zone Data with CQL2>>   | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-cql2-filter
2+| *_For Zone Queries_*
| <<rc_zone-query,Zone Query>>                   | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-query
| <<rc_zone-query-cql2-filter,Filtering Zone Queries with CQL2>> | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-query-cql2-filter
2+| *_OGC API integration_*
| <<rc_root-dggs,Root DGGS>>                     | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/root-dggs
| <<rc_collection-dggs,Collection DGGS>>         | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/collection-dggs
| <<rc_operation-ids,Operation IDs>>             | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/operation-ids
2+| *_Zone Data Encodings_*
| <<rc_data-json,DGGS-JSON Data>>                | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-json
| <<rc_data-ubjson,DGGS-UBJSON Data>>            | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-ubjson
| <<rc_data-dggs-jsonfg,DGGS-JSON-FG Data>>      | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-dggs-jsonfg
| <<rc_data-dggs-ubjsonfg,DGGS-UBJSON-FG Data>>  | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-dggs-ubjsonfg
| <<rc_data-geojson,GeoJSON Data>>               | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-geojson
| <<rc_data-geotiff,GeoTIFF Data>>               | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-geotiff
| <<rc_data-netcdf,netCDF Data>>                 | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-netcdf
| <<rc_data-coveragejson,CoverageJSON Data>>     | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-coveragejson
| <<rc_data-zarr,Zarr Data>>                     | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-zarr
| <<rc_data-jpegxl,JPEG XL Data>>                | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-jpegxl
| <<rc_data-png,PNG Data>>                       | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/data-png
2+| *_Zone List Encodings_*
| <<rc_zone-html,HTML Zone List>>                | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-html
| <<rc_zone-uint64,64-bit Binary Zone List>>     | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-uint64
| <<rc_zone-geojson,GeoJSON Zone List>>          | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-geojson
| <<rc_zone-geotiff,GeoTIFF Zone List>>          | https://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/zone-geotiff
|===
