[[rc-table_data-retrieval]]
[requirements_class]
.Requirements Class Data Retrieval
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-retrieval
subject:: Web API
inherit:: https://www.opengis.net/spec/ogcapi-common-1/1.0/req/core
requirement:: /req/data-retrieval/zone-data
====

=== Retrieving data from a zone (`../dggs/{dggrsId}/zones/{zoneId}/data`)

The following requirements describe how a client can retrieve data from a single DGGS zone
at the resource path `.../dggs/{dggrsId}/zones/{zoneId}/data`.

[[req_data-retrieval_zone-data]]

[requirement]
====
[%metadata]
identifier:: /req/data-retrieval/zone-data
description:: For retrieving data for a single DGGS zone:
part:: The Implementation SHALL support an HTTP GET operation at a resource path ending with `.../dggs/{dggrsId}/zones/{zoneId}/data`.
part:: The Implementation SHALL include a templated link to this resource path in the "Core" `.../dggs/{dggrsId}` resource link templates, and regular link in the `.../dggs/{dggrsId}/zones/{zoneId}` resource links
using the link relation type `[ogc-rel:dggrs-zone-data]` for all zones for which data is available.
part:: The response of the HTTP GET operation SHALL have a status code of 200.
part:: The content of the response SHALL be a data packet corresponding precisely to the area covered by the DGGS zone.
part:: The selection of an encoding for the response SHALL be consistent with HTTP content negotiation.
part:: The `.../dggs/{dggrsId}` resource SHALL include a `defaultDepth` property indicating the Implementation's default depth for when the `zone-depth` query parameter is omitted.
This default value could be any valid value and/or form as defined in the `/req/data-custom-depths/zone-depth-parameter` requirement (single depth, range of depths, or list of depths, relative to the `{zoneId}` hierarchy level).
part:: Unless a `zone-depth` query parameter is specified, the response SHALL return a data packet consistent with this `defaultDepth` property, in accordance with the capabilities of the negotiated data packet encoding.
====

See also <<_retrieving_data_for_a_dggrs_zone, Examples C.8>>.

=== Recommendation for a `crs` query parameter

The following recommendation describe how a server should support a `crs` query parameter for the `.../zones/{zoneId}/data` resource if the data can be returned in multiple applicable CRSs.

[[rec_data-retrieval_crs]]

[recommendation]
====
[%metadata]
identifier:: /rec/data-retrieval/crs
description:: For retrieving data in alternate CRSs:
part:: If the data is available in multiple CRSs, the Implementation SHOULD support a `crs` query parameter for the resource path ending with `.../dggs/{dggrsId}/zones/{zoneId}/data`.
part:: The value of this query parameter SHOULD support values for this query parameter specified either as full URIs (e.g., `http://www.opengis.net/def/crs/OGC/1.3/CRS84`) or as CURIEs (e.g., `[OGC:CRS84]`, `[EPSG:4326]`).
part:: The list of supported CRSs SHOULD be included in a `crs` property of the DGGS origin resource (such as the collection description) as an array of URIs or CURIEs.
====
