[[rc_data-retrieval]]
[requirements_class]
====
[%metadata]
label:: http://www.opengis.net/spec/ogcapi-dggs-1/0.0/req/data-retrieval
subject:: Web API
inherit:: http://www.opengis.net/spec/ogcapi-common-1/1.0/req/core
====

=== Requirements

==== Retrieving data from a zone (`../dggs/{dggsId}/zones/{zoneId}/data`)

The following requirements describe how a client can retrieve data from a single DGGS zone
at the resource path `.../dggs/{dggsId}/zones/{zoneId}/data`.

[[req_data-retrieval_single-zone-data]]

[requirement]
====
[%metadata]
label:: /req/data-retrieval/zone-data
description:: For retrieving data for a single DGGS zone:
part:: The operation SHALL support an HTTP GET operation at a resource path
ending with `.../dggs/{dggsId}/zones/{zoneId}/data`.
part:: The operation SHALL satisfy requirement <<req_data-retrieval_zone-depth-definition,/req/data-retrieval/rc-zone-depth-definition>>.
part:: The operation SHALL provide a templated  link to this resource path using
the link relation type http://www.opengis.net/def/rel/ogc/1.0/dggs-zone-data.
part:: The response of the HTTP GET operation SHALL have a status code of 200.
part:: The content of the response SHALL be a data packet corresponding precisely to the area
covered by the DGGS zone.
part:: The response SHALL satisfy requirement <<req_data-retrieval_zone-depth-response,/req/data-retrieval/rc-zone-depth-response>>.
part:: The selection of an encoding for the response SHALL be consistent with HTTP content negotiation.
====

==== Parameter `zone-depth`

[requirement]
====
[%metadata]
label:: /req/data-retrieval/zone-depth-parameter

description:: Parameter to specify the DGGS resolution levels beyond the specified DGGS zone's hierarchy level to include in the response, when retrieving data for that zone

part:: The implementation SHALL support a `zone-depth` parameter for the HTTP GET operation on a resource path ending with `.../dggs/{dggsId}/zones/{zoneId}/data`.

part:: The implementation SHALL accept the following types of values for the `zone-depth` parameter:
- A single positive integer value - representing a specific zone depth to return (e.g., `zone-depth=5`);
- A range of positive integer values in the form "{low}-{high}" - representing a continuous range of zone depths to return (e.g., `zone-depth=1-8`); or,
- A comma separated list of at least two (2) positive integer values - representing a set of specific zone depths to return (e.g., `zone-depth=1,3,7`).
Some or all of these forms of the `zone-depth` parameter may not be supported with particular data packet encodings
(the data encoding may support a fixed depth, a range of depths, and/or an arbitrary selection of depths).

part:: For each zone depth to be included in the response, the interpretation of a selected depth (whether requesting a single depth, a range of depths, or a list of depths) SHALL be:
- 0 corresponding to a single set of range (properties / field) value(s) for the requested zone,
- 1 corresponding to all zones of the next deeper hierarchy level associated with the requested zone by the indexing scheme,
- ..
- _n_ corresponding to all zones for the _n_'th deeper level in the hierarchy level associated with the requested zone by the indexing scheme.

part:: The association of zones of deeper hierarchy levels with the requested zone SHALL be based on the DGGS reference system,
which takes into consideration both the grid definition as well as the indexing system in use for the DGGS resource.

part:: If a `zone-depth` is specified, the operation SHALL return the data at the resolution(s) / scale(s) specified.

part:: If the `zone-depth` parameter is omitted, the default value described in the DGGS reference system resource (`.../dggs/{dggsId}`) SHALL be assumed by the server, in accordance with the capabilities of the data packet encoding.
This default value which could be any valid value and/or form as defined above (single depth, range of depths, or list of depths).
====

NOTE: A use case for a `zone-depth` of 0 would be to query the single set of values for a specific DGGS zone.

NOTE: For use cases such as visualization and performing analysis over a certain area,
a non-zero `zone-depth` would normally be used to avoid an overwhelming number of server round-trips.
In this case, more than a single value would be returned for each zone request,
with values returned for descendent zones at `zone-depth` levels deeper than the requested zone's level.
For example, requesting data for a level 10 zone with a `zone-depth` of 8 would return
individual values for each level 18 zones contained within that level 10 zone being requested.

==== Parameter `subset`

[requirement]
====
[%metadata]
label:: /req/data-retrieval/subset
description:: For specifying a multi-dimensional subset for the zone data being retrieved:
part:: The Implementation SHALL support a `subset` query parameter for the zone data retrieval operation (resource path ending with `.../dggs/{dggsId}/zones/{zoneId}/data`)
conforming to the following Augmented Backus Naur Form (ABNF) fragment:

[source,ABNF]
----
  SubsetSpec:       "subset"=axisName(intervalOrPoint)
  axisName:         {text}
  intervalOrPoint:  interval \| point
  interval:         low : high
  low:              point \| *
  high:             point \| *
  point:            {number} \| "{text}"

  Where:
     \" = double quote = ASCII code 0x42,
     {number} is an integer or floating-point number, and
     {text} is some general ASCII text (such as a time and date notation in ISO 8601).
----
part:: The implementation SHALL support as axis names `Lat` and `Lon` for geographic CRS and `x` and `y` for projected CRS, which are to be interpreted as the best matching spatial axis in the CRS definition.
part:: If a third spatial dimension is supported (if the resource's spatial extent bounding box is three dimensional), the implementation SHALL also support a `h` dimension (elevation above the ellipsoid in EPSG:4979 or CRS84h) for geographic CRS and `z` for projected CRS, which are to be interpreted as the vertical axis in the CRS definition.
part:: The implementation SHALL return a 400 error status code if an axis name does not correspond to one of the axes of the Coordinate Reference System (CRS) of the target resource.
part:: For a CRS where an axis can wrap around, such as subsetting across the dateline (anti-meridian) in a geographic CRS, a _low_ value greater than _high_ SHALL
be supported to indicate an extent crossing that wrapping point.
part:: The implementation SHALL interpret the coordinates as values for the named axis of the CRS specified in the `subset-crs` parameter value or in http://www.opengis.net/def/crs/OGC/1.3/CRS84 (http://www.opengis.net/def/crs/OGC/1.3/CRS84h for vertical dimension) if the `subset-crs` parameter is missing.
part:: If the `subset` parameter including any of the dimensions corresponding to those of the map bounding box is used with a `bbox`, the server SHALL return a 400 client error.
part:: The implementation SHALL interpret multiple `subset` parameters, as if all dimension subsetting values were provided in a single `subset` parameter (comma separated).
Example: `subset=Lat(-90:90)&subset=Lon(-180:180)` is equivalent to `subset=Lat(-90:90),Lon(-180:180)`
====

NOTE: A subset parameter for http://www.opengis.net/def/crs/OGC/1.3/CRS84 will read as subset=Lon(left_lon:right_lon),Lat(lower_lat:upper_lat).

NOTE: When the _inteval_ values fall partially outside of the range of valid values defined by the CRS for the identified axis, the service is expected to return the non-empty portion of the resource resulting from the subset.

==== Parameter `datetime`

[requirement]
====
[%metadata]
label:: /req/data-retrieval/datetime
description:: For specifying a multi-dimensional subset for which to retrieve data from a zone:
part:: The Implementation SHALL support a `subset` query parameter for the zone data retrieval operation (resource path ending with `.../dggs/{dggsId}/zones/{zoneId}/data`)
conforming to the following Augmented Backus Naur Form (ABNF) fragment:
[source,ABNF]
----
  SubsetSpec:       "subset"=axisName(intervalOrPoint)
  axisName:         {text}
  intervalOrPoint:  interval \| point
  interval:         low : high
  low:              point \| *
  high:             point \| *
  point:            {number} \| "{text}"

  Where:
     \" = double quote = ASCII code 0x42,
     {number} is an integer or floating-point number, and
     {text} is some general ASCII text (such as a time and date notation in ISO 8601).
----
part:: The implementation SHALL support as axis names `Lat` and `Lon` for geographic CRS and `x` and `y` for projected CRS, which are to be interpreted as the best matching spatial axis in the CRS definition.
part:: If a third spatial dimension is supported (if the resource's spatial extent bounding box is three dimensional), the implementation SHALL also support a `h` dimension (elevation above the ellipsoid in EPSG:4979 or CRS84h) for geographic CRS and `z` for projected CRS, which are to be interpreted as the vertical axis in the CRS definition.
part:: The implementation SHALL return a 400 error status code if an axis name does not correspond to one of the axes of the Coordinate Reference System (CRS) of the target resource.
part:: For a CRS where an axis can wrap around, such as subsetting across the dateline (anti-meridian) in a geographic CRS, a _low_ value greater than _high_ SHALL
be supported to indicate an extent crossing that wrapping point.
part:: The implementation SHALL interpret the coordinates as values for the named axis of the CRS specified in the `subset-crs` parameter value or in http://www.opengis.net/def/crs/OGC/1.3/CRS84 (http://www.opengis.net/def/crs/OGC/1.3/CRS84h for vertical dimension) if the `subset-crs` parameter is missing.
part:: If the `subset` parameter including any of the dimensions corresponding to those of the map bounding box is used with a `bbox`, the server SHALL return a 400 client error.
part:: The implementation SHALL interpret multiple `subset` parameters, as if all dimension subsetting values were provided in a single `subset` parameter (comma separated).
Example: `subset=Lat(-90:90)&subset=Lon(-180:180)` is equivalent to `subset=Lat(-90:90),Lon(-180:180)`
====

NOTE: A subset parameter for http://www.opengis.net/def/crs/OGC/1.3/CRS84 will read as subset=Lon(left_lon:right_lon),Lat(lower_lat:upper_lat).

NOTE: When the _inteval_ values fall partially outside of the range of valid values defined by the CRS for the identified axis, the service is expected to return the non-empty portion of the resource resulting from the subset.

