[[rc_table-zone_geojson]]

[requirements_class]
.Requirements Class GeoJSON Zone List
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/zone-geojson
subject:: Web API
inherit:: <<rfc7946, GeoJSON>>
inherit:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/zone-query
requirement:: /req/zone-geojson/content
====

[requirement]
====
[%metadata]
identifier:: /req/zone-geojson/content
part:: Every 200 response of the server for zone query with the media type `application/geo+json` SHALL be a GeoJSON document consisting of a FeatureCollection, where every Feature represents a single zone.
part:: Every feature SHALL have a `zoneID` property corresponding to the textual identifer of the zone.
part:: The geometry of each feature SHALL be the geometry of the zone.
====

[recommendation]
====
[%metadata]
identifier:: /rec/zone-geojson/id
part:: The Feature `id` SHOULD be a sequential identifier starting at 1, have the same text value as the `zoneID` property, or correspond to the 64-bit integer identifier for the zone.
====

[recommendation]
====
[%metadata]
identifier:: /rec/zone-geojson/mid-points
part:: For DGGRSs not in CRS84, the geometry SHOULD include intermediate points between the vertices of the zone geometry so as to accurately represent the shape of the zones.
====

[recommendation]
====
[%metadata]
identifier:: /rec/zone-geojson/geometry
part:: The implementation SHOULD support a `geometry` query parameter allowing a client to choose how to return the geometry of each zone.
part:: The implementation SHOULD support a value of `geometry=zone-centroid` to request a representation where the geometry of each a zone is a Point geometry for the centroid of that zone.
part:: The implementation SHOULD support a value of `geometry=zone-region` to request a representation where the geometry of each zone is a (Multi)Polygon geometry.
part:: The implementation SHOULD support a value of `geometry=none` to request a representation with a null geometry.
part:: If a requested geometry representation is not supported, the implementation SHOULD return a 4xx or 501 "Not Implemented" HTTP error.
====
