[[rc_table-data_png]]

[requirements_class]
.Requirements Class PNG Data
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-png
subject:: Web API
inherit:: <<PNG_ISO_IEC_15948>>
inherit:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-retrieval
requirement:: /req/data-png/content
====

[requirement]
====
[%metadata]
identifier:: /req/data-png/content
description:: For encoding zone data as PNG
part:: Every 200 response of the server for zone data with the media type `image/png` SHALL be a PNG image representing the data values for all selected fields within the zone for which data is requested.
part:: If the zone geometry is not rectangular, the closest bounding rectangle SHALL be used for referencing the image.
part:: A distinct value for each sub-zone implied from the requested `zone-depth` SHALL correspond to at least one distinct cell value in the response.
part:: For Implementations supporting Data Custom Depths, each depth of the requested zone depth pyramid SHALL be a separate image (overview) in the response.
part:: A `Values-Scale:` response header with a numeric real value SHALL be returned indicating the factor by which values were multiplied before an offset was added to result in the encoded 8-bit or 16-bit PNG unsigned integer values.
part:: A `Values-Offset:` response header with a numeric real value SHALL be returned indicating the offset which was added after multiplying values by the scale factor to result in the encoded 8-bit or 16-bit PNG unsigned integer values.
====

[recommendation]
====
[%metadata]
identifier:: /rec/data-png/null-values
part:: Null values SHOULD be used for cells lying outside the zone geometry.
====

[recommendation]
====
[%metadata]
identifier:: /rec/data-png/crs
part:: The CRS of the response SHOULD be consistent with either the DGGRS or the underlying geographic CRS (e.g., CRS84).
====

[recommendation]
====
[%metadata]
identifier:: /rec/data-png/scale-offset
part:: The Implementation SHOULD support a `values-scale` query parameter on Zone data resources when requesting a PNG output to indicate the value scale factor, as described in the `Values-Scale` response header part of the content requirement.
part:: The Implementation SHOULD support a `values-offset` query parameter on Zone data resources when requesting a PNG output to indicate the value offset, as described in the `Values-Offset` response header part of the content requirement.
====
