[[rc-table_data-cql2-filter]]
[requirements_class]
.Requirements Class Filtering Zone Data with CQL2
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-cql2-filter
subject:: Web API
inherit:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-retrieval
inherit:: https://www.opengis.net/spec/cql2/1.0/req/cql2-text
requirement:: /req/data-cql2-filter/filter
====

=== Parameter `filter`

The following requirements describe how a client can specify a filtering CQL2 expression to apply on a zone data retrieval request.

[requirement]
====
[%metadata]
identifier:: /req/data-cql2-filter/filter
description:: For specifying a CQL2 expression filtering the data returned from a zone data request:
part:: The Implementation SHALL support a `filter` query parameter specified using the CQL2-Text encoding of the OGC Common Query Language for the zone data retrieval
operation (resource path ending with `.../dggs/{dggrsId}/zones/data`).
part:: For a rasterized representation, the data returned SHALL have null or NODATA values for sub-zones where the CQL2 expression evaluates to false when considering the geometry and the data of that sub-zone.
part:: For a vector representation, the data returned SHALL only include features where the CQL2 expression evaluates to true when considering the geometry and the data of that sub-zone.
part:: The CQL2 expression evaluator SHALL support the queryables declared in the JSON Schema resource linked to from the origin of the DGGRS resources using the `[ogc-rel:queryables]` link relation type.
====

NOTE: The available queryables would typically include the fields of the data source being returned in the response.

See also <<_filtering_zone_data_using_cql2_expressions, Examples C.9.4>>.
