[[rc-table_zone-query-cql2-filter]]
[requirements_class]
.Requirements Class Filtering Zone Queries with CQL2
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/zone-query-cql2-filter
subject:: Web API
inherit:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/zone-query
inherit:: https://www.opengis.net/spec/cql2/1.0/req/cql2-text
requirement:: /req/zone-query-cql2-filter/filter
====

=== `filter` query parameter

The following requirements describe how a client can specify a filtering CQL2 expression querying a list of zones.

[requirement]
====
[%metadata]
identifier:: /req/zone-query-cql2-filter/filter
description:: For specifying a CQL2 expression filtering the zones returned from a zone query:
part:: The Implementation SHALL support a `filter` query parameter specified using the CQL2-Text encoding of the OGC Common Query Language for the zone query
operation (resource path ending with `.../dggs/{dggrsId}/zones`).
part:: The list of returned zones SHALL only be those for which the CQL2 expression evaluates to true when considering the geometry and the data of the DGGS zones resource being queried.
part:: The CQL2 expression evaluator SHALL support the queryables declared in the JSON Schema resource linked to from the origin of the DGGRS resources using the `[ogc-rel:queryables]` link relation type.
====

NOTE: The available queryables would typically include the fields of the data source, which may also be retrieved using the <<rc_data-retrieval, Data Retrieval>> requirements class.

See also <<_filtering_zone_queries_using_cql2_expressions, Examples C.7>>.
