[[rc_table-data_dggs_ubjsonfg]]

[requirements_class]
.Requirements Class DGGS-UBJSON-FG
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-dggs-ubjsonfg
subject:: Web API
inherit:: https://ubjson.org/[https://ubjson.org/]
inherit:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-retrieval
inherit:: https://www.opengis.net/spec/json-fg-1/0.3/req/core
requirement:: /req/data-dggs-ubjsonfg/content
====

[requirement]
====
[%metadata]
identifier:: /req/data-dggs-ubjsonfg/content
description:: For encoding zone data as DGGS-UBJSON-FG
part:: The Implementation SHALL support zone data requests negotiating an `application/geo+ubjson` media type combined with a `profile` query parameter with a value of `jsonfg-dggs`, `jsonfg-dggs-plus`, `jsonfg-dggs-zoneids` or `jsonfg-dggs-zoneids-plus` allowing a client to request a DGGS-UBJSON-FG response.
part:: Every 200 response of the server for DGGS-FG-UBJSON zone data requests SHALL be a https://ubjson.org/[Universal Binary JSON] document representing the vector features within the requested zone
part:: The content of the UBJSON document SHALL follow all the of same requirements as for DGGS-JSON-FG described above.
====
