[[rc_table-zone_json]]

[requirements_class]
.Requirements Class JSON Zone List
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/zone-json
subject:: Web API
inherit:: <<rfc8259, JSON>>
inherit:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/zone-query
====

[requirement]
====
[%metadata]
identifier:: /req/zone-json/content
part:: Every 200 response of the server for zone query with the media type `application/json` SHALL be a JSON document listing the textual identifiers for all zones matching the query.
part:: The schema for the JSON document SHALL follow the JSON Schema for DGGS Zone Query described below, where the zone identifiers are strings within a `zones` array property.
part:: The `links` property SHALL include an `[ogc-rel:dggrs]` link to the Discrete Global Grid Reference System description resource.
part:: The `links` property SHALL include an `[ogc-rel:dggrs-definition]` link to the DGGRS definition, using the schema defined in <<annex-dggrs-def, Annex B - DGGRS Definitions>> or a later version.
====

.JSON Schema for a DGGS Zone Query response
[source,json]
----
{
   "$schema" : "https://json-schema.org/draft/2020-12/schema",
   "$id" : "https://schemas.opengis.net/ogcapi/dggs/part1/1.0/openapi/schemas/dggs-core/dggs-zones.json",
   "type": "object",
   "required": [ "zones" ],
   "properties":
   {
      "zones" : { "type": "array", "items": { "type": "string" } },
      "links" :
      {
         "description": "Links to related resources."
         "items": { "$ref" : "https://schemas.opengis.net/ogcapi/dggs/part1/1.0/openapi/schemas/common-core/link.yaml"
      }
   }
}
----

[recommendation]
====
[%metadata]
identifier:: /rec/zone-json/additional-links
part:: If _DGGS Zone Data Retrieval_ is supported, the `linkTemplates` property SHOULD include an `[ogc-rel:dggrs-zone-data]` link with a `{zoneId}` variable to retrieve data from each of these DGGRS zones.
part:: The `links` property SHOULD include an `[ogc-rel:geodata]` link for zone listing pertaining to a particular collection (for <<rc_collection-dggs,Collection DGGS requirement class>>).
====

[recommendation]
====
[%metadata]
identifier:: /rec/zone-json/zone-order
part:: For responses where zones of multiple hierarchy levels are returned when `compact-zones` is true, the zones SHOULD be listed with the coarser resolution level first (larger zones).
====
