[[rc_table-data_netcdf]]

[requirements_class]
.Requirements Class NetCDF
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-netcdf
subject:: Web API
inherit:: <<OGC10-090r3, OGC Network Common Data Form (NetCDF) Core Encoding Standard version 1.0>>
inherit:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-retrieval
requirement:: /req/data-netcdf/content
====

[requirement]
====
[%metadata]
identifier:: /req/data-netcdf/content
part:: Every 200 response of the server for zone data with the media type `application/netcdf` SHALL be a netCDF file representing the data values for all selected fields for a single zone.
part:: The response SHALL be encoded using a netCDF encoding extension, such as the https://portal.ogc.org/files/?artifact_id=43734[NetCDF classic and 64-bit offset format], or netCDF version 4 based on
https://docs.ogc.org/is/18-043r3/18-043r3.html[OGC HDF5] (the selection of a particular netCDF format / version could be negotiated through media type parameters or some other mechanism).
part:: If the netCDF data incorporates georeferencing information, this information SHALL be consistent with the DGGRS Zone ID.
part:: If the zone geometry is not rectilinear, the closest bounding rectangle (or volume) SHALL be used for referencing the data.
part:: A distinct value for each sub-zone implied from the requested `zone-depth` SHALL correspond to at least one distinct cell value in the response.
====

[recommendation]
====
[%metadata]
identifier:: /rec/data-netcdf/null-values
part:: Null values SHOULD be used for cells lying outside the zone geometry.
====

[recommendation]
====
[%metadata]
identifier:: /rec/data-netcdf/crs
part:: The spatial reference of the response, determined by the units of the coordinate variables and whether or not the `grid_mapping` attribute exists, as well
as any applicable extension in use such as https://portal.ogc.org/files/?artifact_id=51908[CF-netCDF], SHOULD be consistent with either the DGGRS or the underlying geographic CRS (e.g., CRS84).
====
