[[rc-table_data-custom-depths]]
[requirements_class]
.Requirements Class Data Custom Depths
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-custom-depths
subject:: Web API
inherit:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-retrieval
requirement:: /req/data-custom-depths/zone-depth
====

=== `zone-depth` query parameter

[requirement]
====
[%metadata]
identifier:: /req/data-custom-depths/zone-depth

description:: Query parameter to specify the DGGS refinement levels beyond the specified DGGS zone's refinement level to include in the response, when retrieving data for that zone

part:: The Implementation SHALL support a `zone-depth` query parameter for the HTTP GET operation on a resource path ending with `.../dggs/{dggrsId}/zones/{zoneId}/data`.

part:: The Implementation SHALL accept the following types of values for the `zone-depth` query parameter:
- A single positive integer value - representing a specific zone depth to return (e.g., `zone-depth=5`);
- A range of positive integer values in the form "{low}-{high}" - representing a continuous range of zone depths to return (e.g., `zone-depth=1-8`); or,
- A comma separated list of at least two (2) positive integer values - representing a set of specific zone depths to return (e.g., `zone-depth=1,3,7`).
Some or all of these forms of the `zone-depth` query parameter may not be supported with particular data packet encodings
(the data encoding may support a fixed depth, a range of depths, and/or an arbitrary selection of depths).

part:: For each zone depth to be included in the response, the interpretation of a selected depth (whether requesting a single depth, a range of depths, or a list of depths) SHALL be:
- 0 corresponding to a single set of range (properties / field) value(s) for the requested zone,
- 1 corresponding to all zones of the next deeper hierarchy level associated with the requested zone by the indexing scheme,
- ..
- _n_ corresponding to all zones for the _n_'th deeper level in the hierarchy level associated with the requested zone by the indexing scheme.

part:: The association of zones of deeper hierarchy levels with the requested zone SHALL be based on the DGGRS reference system,
which takes into consideration both the grid definition as well as the indexing system in use for the DGGS resource.

part:: If a `zone-depth` is specified, the operation SHALL return the data at the refinement level(s) specified.
====

NOTE: A use case for a `zone-depth` of 0 would be to query the single set of values for a specific DGGS zone.

NOTE: For use cases such as visualization and performing analysis over a certain area,
a non-zero `zone-depth` would normally be used to avoid an overwhelming number of server round-trips.
In this case, more than a single value would be returned for each zone request,
with values returned for descendent zones at `zone-depth` levels deeper than the requested zone's level.
For example, requesting data for a level 10 zone with a `zone-depth` of 8 would return
individual values for each level 18 zones contained within that level 10 zone being requested.

[recommendation]
====
[%metadata]
identifier:: /rec/data-custom-depths/beyond-max-depth
description:: For informing clients of a maximum relative depth:
part:: For DGGS resources associated with a data source, the Implementation SHOULD include a `maxRelativeDepth` integer property in the `.../dggs/{dggrsId}` resource specifying the maximum relative depth at which data can be retrieved.
part:: The Implementation SHOULD return a 4xx error for data retrieval beyond the `maxRelativeDepth` specified in the DGGRS description associated with the request.
====

See also <<examples_requesting_data_at_a_particular_relative_depth, Examples C.9>>.
