[[rc_table-zone_geojson]]

[requirements_class]
.Requirements Class GeoJSON Zone List
====
[%metadata]
identifier:: http://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/zone-geojson
subject:: Web API
inherit:: <<rfc7946, GeoJSON>>
inherit:: http://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/zone-query
====

[requirement]
====
[%metadata]
identifier:: /req/zone-geojson/content
part:: Every 200 response of the server for zone query with the media type `application/geo+json` SHALL be a GeoJSON document consisting of a FeatureCollection, where every Feature represents a single zone.
part:: Every feature SHALL have a `zoneID` property corresponding to the textual identifer of the zone.
part:: The geometry of each feature SHALL be the geometry of the zone.
====

[recommendation]
====
[%metadata]
identifier:: /rec/zone-geojson/id
part:: The Feature `id` SHOULD have the same value as the `zoneID` property or use the 64-bit integer identifier.
====

[recommendation]
====
[%metadata]
identifier:: /rec/zone-geojson/mid-points
part:: For DGGRSs not in CRS84, the geometry SHOULD include intermediate points between the vertices of the zone geometry so as to accurately represent the shape of the zones.
====
