[[rc_table-data_jpegxl]]

[requirements_class]
.Requirements Class JPEG XL Data
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-jpegxl
subject:: Web API
inherit:: <<JPEG_XL1>>
inherit:: <<JPEG_XL2>>
inherit:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-retrieval
requirement:: /req/data-jpegxl/content
====

[requirement]
====
[%metadata]
identifier:: /req/data-jpegxl/content
part:: Every 200 response of the server for zone data with the media type `image/jxl` SHALL be a https://jpeg.org/jpegxl/[JPEG XL] image representing the data values for all selected fields for a single zone.
part:: If the zone geometry is not rectangular, the closest bounding rectangle SHALL be used for referencing the image.
part:: A distinct value for each sub-zone implied from the requested `zone-depth` SHALL correspond to at least one distinct cell value in the response.
part:: For implementations supporting Data Custom Depths, each depth of the requested zone depth pyramid SHALL be a separate image (overview) in the response.
====

[recommendation]
====
[%metadata]
identifier:: /rec/data-jpegxl/null-values
part:: Null values SHOULD be used for cells lying outside the zone geometry.
====

[recommendation]
====
[%metadata]
identifier:: /rec/data-jpegxl/crs
part:: The CRS of the response SHOULD be consistent with either the DGGRS or the underlying geographic CRS (e.g., CRS84).
====
