[[rc-table_data-subsetting]]
[requirements_class]
.Requirements Class Data Subsetting
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-subsetting
subject:: Web API
inherit:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-retrieval
requirement:: /req/data-subsetting/subset
requirement:: /req/data-subsetting/datetime
requirement:: /req/data-subsetting/properties
====

=== Parameter `subset`

[requirement]
====
[%metadata]
identifier:: /req/data-subsetting/subset
description:: For specifying a multi-dimensional subset for the zone data being retrieved (excluding dimensions of the discrete global grid reference system):
part::
+
--
The Implementation SHALL support a `subset` query parameter for the zone data retrieval operation (resource path ending with `.../dggs/{dggrsId}/zones/{zoneId}/data`)
conforming to the following Augmented Backus Naur Form (ABNF) fragment:

[source,ABNF]
----
  SubsetSpec:       "subset"=axisName(intervalOrPoint)
  axisName:         {text}
  intervalOrPoint:  interval \| point
  interval:         low : high
  low:              point \| *
  high:             point \| *
  point:            {number} \| "{text}"

  Where:
     \" = double quote = ASCII code 0x42,
     {number} is an integer or floating-point number, and
     {text} is some general ASCII text (such as a time and date notation in ISO 8601).
----
--
part:: The Implementation SHALL support as an axis names`time` for a temporal dataset, unless this temporal axis is an axis of the discrete global grid reference system.
part:: If a third vertical spatial dimension is supported (if the resource's spatial extent bounding box is three dimensional) and that dimension is not part of the discrete global grid system definition, the Implementation SHALL also support a `h` dimension (elevation above the ellipsoid in EPSG:4979 or CRS84h) for geographic CRS and `z` for projected CRS, which are to be interpreted as the vertical axis in the CRS definition.
part:: The Implementation SHALL support as axis names any additional dimension (beyond spatial and temporal) as described in the `extent` property of the collection or dataset description.
part:: The Implementation SHALL return a 400 error status code if an axis name does not correspond to one of the axes of the Coordinate Reference System (CRS) of the data or an axis defined in the relevant `extent` property.
part:: If a `subset` parameter including any of the dimensions corresponding to the axes of the discrete global grid reference system is used, the server SHALL return a 400 client error.
part:: The Implementation SHALL interpret multiple `subset` parameters, as if all dimension subsetting values were provided in a single `subset` parameter (comma separated).
Example: `subset=time("2018-02-12T16:00:0Z":"2018-02-12T20:00:00Z")&subset=atm_pressure_hpa(500:750)` is equivalent to `subset=time("2018-02-12T16:00:0Z":"2018-02-12T20:00:00Z"),atm_pressure_hpa(500:750)`
====

NOTE: When the _interval_ values fall partially outside of the range of valid values defined by the CRS for the identified axis, the service is expected to return the non-empty portion of the data resulting from the subset.

=== Parameter `datetime`

[requirement]
====
[%metadata]
identifier:: /req/data-subsetting/datetime
description:: For specifying a time instant or interval for which to retrieve data from a zone for a non-temporal DGGS:
part::
+
--
The Implementation SHALL support a `datetime` parameter expressed corresponding to either a date-time instant or a time interval, conforming to the following syntax (using link:https://tools.ietf.org/html/rfc5234[ABNF]):

[source]
----
interval-bounded       = instant "/" instant
interval-bounded-start = [".."] "/" instant
interval-bounded-end   = instant "/" [".."]
interval-unbounded     = [".."] "/" [".."]
interval               = interval-bounded / interval-bounded-start / interval-bounded-end / interval-unbounded
datetime               = instant / interval
----
--
part:: The implementation SHALL support an `instant` defined as specified by link:https://tools.ietf.org/html/rfc3339#section-5.6[RFC 3339, 5.6], with the exception that the server is
only required to support the `Z` UTC time notation, and not required to support local time offsets.
part:: Only the portions of the data within the specified interval SHALL be part of the zone data response, performing a trim operation for an interval or a slicing operation for an instant (in the case of a gridded coverage), or a filtering operation for feature data.
part:: Time intervals unbounded at the start or at the end SHALL be supported using a double-dot (`..`) or an empty string for the start/end.
part:: If a `datetime` parameter is specified requesting zone data where no temporal dimension applies, the Implementation SHALL either ignore the parameter or return a 4xx client error.
====

Note: ISO 8601-2 distinguishes unbounded start/end timestamps (double-dot) and unknown start/end timestamps (empty string). For queries, an unspecified start/end has the same effect as an unbounded start/end.

*Examples:*

.A date-time
=================
February 12, 2018, 23:20:52 GMT:

`datetime=2018-02-12T23:20:52Z`
=================

.Intervals
=================
February 12, 2018, 00:00:00 GMT to March 18, 2018, 12:31:12 GMT:

`datetime=2018-02-12T00:00:00Z/2018-03-18T12:31:12Z`

February 12, 2018, 00:00:00 UTC or later:

`datetime=2018-02-12T00:00:00Z/..`

March 18, 2018, 12:31:12 UTC or earlier:

`datetime=../2018-03-18T12:31:12Z`
=================

=== Parameter `properties`

[requirement]
====
[%metadata]
identifier:: /req/data-subsetting/properties
description:: For specifying fields to include when retrieving zone data
part:: The zone data retrieval operation SHALL support a parameter `properties` where the value is a comma-separated list of fields to be returned.
part:: The Implementation SHALL support selecting a field using the identifier corresponding to the top-level property keys of the logical schema of the resource associated with the DGGRS zone data request, and return 400 status code for an unrecognized selected field.
part:: Only the selected fields SHALL be returned from the zone data request.
part:: If the zone data encodings response can self-describe its list of fields (as with the `schema` property of the DGGS-JSON encoding), the field description SHALL correspond to the requested list of fields.
part:: If the negotiated format of the response has a concept of field order, then the fields SHALL be in the same order as the requested list of selected fields.
====

=== Parameter `exclude-properties`

[requirement]
====
[%metadata]
identifier:: /req/data-subsetting/exclude-properties
description:: For including all but specific fields when retrieving zone data
part:: The zone data retrieval operation SHALL support a parameter `exclude-properties` where the value is a comma-separated list of fields not to be returned.
part:: The Implementation SHALL support selecting fields not to return using the identifier corresponding to the top-level property keys of the logical schema of the resource associated with the DGGRS zone data request, and return 400 status code for an unrecognized selected field.
part:: All but the selected fields SHALL be returned from the zone data request.
part:: The Implementation SHALL return a 4xx error when using the both the `properties` and `exclude-properties` parameters in the same request.
====
