[[rc_core]]
[requirements_class]
====
[%metadata]
label:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/core
subject:: Web API
====

=== Requirements

==== Listing available DGGRS (`.../dggs`)

[requirement]
====
[%metadata]
label:: /req/core/dggrs-list
description:: For retrieving the list of available discrete global grid reference systems:
part:: The Implementation SHALL support an HTTP GET operation at a resource path ending with `.../dggs`.
part:: The Implementation SHALL support a JSON representation of this `.../dggs` resource.
part:: The `.../dggs` resource SHALL include a `dggrs` array property listing all discrete global grid reference systems supported by the Implementation.
part:: Each element of the `dggrs` array SHALL include a subset of the information available in the individual DGGRS information described below, including at minimum the `id`, `title`, `uri` (if applicable), and `links`.
part:: The `links` property SHALL include at minimum a link to the discrete global grid reference system using the `self` link relation type, as well as a link to the discrete global grid reference system using the `[ogc-rel:dggrs-definition]` relation type.
part:: The link relation type to use for linking from the corresponding resource to the list of available DGGRSs for that resource SHALL be `[ogc-rel:dggrs-list]`.
====

==== Discrete global grid reference system information (`.../dggs/{dggrsId}`)

[requirement]
====
[%metadata]
label:: /req/core/dggrs-info
description:: For retrieving information for a particular available discrete global grid reference system:
part:: The Implementation SHALL support an HTTP GET operation at a resource path ending with `.../dggs/{dggrsId}`.
part:: The Implementation SHALL support a JSON representation of this `.../dggs/{dggrsId}` resource.
part:: The `.../dggs/{dggrsId}` resource SHALL include an `id` property consistent with the `{dggrsId}` resource path parameter.
part:: The `.../dggs/{dggrsId}` resource SHALL include a link to the resource itself using the `self` link relation type.
part:: The `.../dggs/{dggrsId}` resource SHALL include a link to a definition of the discrete global grid reference system (describing both the discrete global grid as well as the particular indexing scheme to identify zones by identifiers),
using the link relation type `[ogc-rel:dggrs-definition]`.
The schema for that definition is likely to evolve in order to support describing a growing number of classes of DGGS.
A first draft of this schema is available in <<annex-dggrs-def, Annex B - Discrete Global Grid Reference System Definitions>>.
part:: The `.../dggs/{dggrsId}` resource SHALL include a templated link in the `linkTemplates` array to request information for a particular zone using the link relation type `[ogc-rel:dggrs-zone-info]` and the template variable `{zoneId}`.
part:: If the discrete global grid reference system (the combination of the discrete global grid and indexing system) is registered with an authority, the resource SHALL include `uri` property corresponding to that registered discrete global grid reference system.
part:: If the discrete global grid reference system is based on a particular coordinate reference system, the resource shall specify that CRS in a `crs` property, preferably as a URI (if one is available).
part:: The Implementation SHALL include a short `title` property identifying the discrete global grid reference system intended for display to a human.
part:: The Implementation SHALL include a `description` property providing a summary description of the discrete global grid reference system.
====

[recommendation]
====
[%metadata]
label:: /rec/core/max-refinement
description:: For specifying a maximum refinement level for a discrete global grid reference system associated with a particular geospatial data resource:
part:: For DGGS resources associated with a data source, the Implementation SHOULD include a `maxRefinementLevel` integer property in the `.../dggs/{dggrsId}` resource specifying the maximum refinement level at which the full resolution of the data can be retrieved (using a `zone-depth` relative depth of 0) and/or used for performing the most accurate zone queries (using that value for `zone-level`).
====

[permission]
====
[%metadata]
label:: /per/core/beyond-max-refinement
description:: For handling requests beyond `maxRefinementLevel`:
part:: The Implementation MAY return a 4xx error for data retrieval and/or zone query requests beyond a `maxRefinementLevel` specified in the DGGRS description associated with the request.
part:: Alternatively, the Implementation MAY process the request by properly oversampling the data values for handling refinement levels beyond the `maxRefinementLevel`.
====

==== Retrieving zone information (`.../dggs/{dggrsId}/zones/{zoneId}`)

[requirement]
====
[%metadata]
label:: /req/core/zone-info
description:: For retrieving information for a particular DGGRS zone:
part:: The Implementation SHALL support an HTTP GET operation at a resource path ending with `.../dggs/{dggrsId}/zones/{zoneId}` providing information for a valid individual zones of the discrete global grid reference system.
part:: The zone information resource SHALL support a JSON representation.
part:: The zone information resource SHALL include an `id` property corresponding to the `{zoneId}` resource path parameter.
part:: The zone information resource SHALL include a link back to the corresponding DGGRS resource (`.../dggs`) using the `[ogc-rel:dggrs]` link relation type.
====

[recommendation]
====
[%metadata]
label:: /rec/core/zone-info
part:: The zone information resource SHOULD include links to its parent(s) zone(s) using link relation `[ogc-rel:dggrs-zone-parent]`.
part:: The zone information resource SHOULD include links to its immediate children zone using link relation `[ogc-rel:dggrs-zone-child]`.
part:: The zone information resource SHOULD include links to its neighboring zones using link relation `[ogc-rel:dggrs-zone-neighbor]`.
part:: The zone information resource SHOULD include an `areaMetersSquare` property indicating the surface area of the zone in square meters.
part:: For a DGGS with three spatial dimension, the zone information resource SHOULD include a `volumeMetersCube` property indicating the volume of the zone in cubic meters.
part:: For a temporal DGGS, the zone information resource SHOULD include a `temporalDurationSeconds` property indicating the amount of time covered by the zone in seconds.
part:: The zone information resource SHOULD include a `geometry` property indicating the 2D and/or 3D spatial geometry of the zone using GeoJSON or OGC Features & Geometry JSON for the JSON encoding,
and including intermediate points between the vertices of the geometry so as to accurately represent the shape of the zones for DGGRSs not in CRS84.
part:: For a temporal DGGS, the zone information resource SHOULD include a `temporalInterval` property indicating the start and end time of the zone.
part:: The implementation SHOULD support a GeoJSON and/or OGC Features & Geometry JSON representation of the zone information resource where the top-level object is a feature representing the zone geometry,
a `zoneID` property of that feature corresponds to the textual identifier (the `{zoneId}`), the `id` of the feature corresponds to either the textural identifier or the 64-bit unsigned integer identifier of the zone,
and the other properties described in this recommendation are properties of that feature.
part:: For a zone associated with a particular collection, the implementation SHOULD provide summary statistics (`minimum`, `maximum`, `average`, `stdDev`) pertaining to this zone for each field (fields of the range of a coverage, or relevant numeric properties of a feature collection) of the data. In the JSON encoding, this SHOULD be implemented as a JSON dictionary mapping field names to an object with each statistic.
part:: For a zone associated with a particular collection, the implementation SHOULD provide `areaMetersSquareWithData`, `volumeMetersCubeWithData`, `temporalDurationSecondsWithData` properties corresponding to
the respective properties defined above for the overall zones, but considering only the portions of the zone where there is data (e.g., regions of the zone excluding NODATA values for a gridded coverage, or within geometry for a feature collection).
====

[recommendation]
====
[%metadata]
label:: /rec/core/robots-txt
part:: Implementations SHOULD include a https://en.wikipedia.org/wiki/Robots.txt[robots.txt] file at the root of their Web API discouraging robots from crawling the DGGS zone resources.
part:: The content of that Robots.txt file SHOULD include `Disallow: \*/dggs/*/zones/*` to prevent crawling all DGGS resources under the `/zones/` resource path.
====

NOTE: The presence of a `robots.txt` file is not a security measure and relies on the voluntary compliance of well-intended crawlers to minimize unnecessary requests.
This measure does not prevent malicious clients from overwhelming the server with numerous requests which may result in Denial of Service attacks.
