[[rc_table-zone_fgjson]]

[requirements_class]
.Requirements Class FG-JSON Zone List
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/zone-fgjson
subject:: Web API
inherit:: <<OGC21-045r1>>
inherit:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/zone-query
requirement:: /req/zone-fgjson/content
====

[requirement]
====
[%metadata]
identifier:: /req/zone-fgjson/content
part:: Every 200 response of the server for zone query with the media type `application/fg+json` SHALL be a Features & Geometry JSON document consisting of a FeatureCollection, where every Feature represents a single zone.
part:: Every feature SHALL have a `zoneID` property corresponding to the textual identifier of the zone.
part:: The geometry of each feature SHALL be the geometry of the zone.
====

[recommendation]
====
[%metadata]
identifier:: /rec/zone-fgjson/id
part:: The Feature `id` SHOULD have the same value as the `zoneID` property or use the 64-bit integer identifier.
====

[recommendation]
====
[%metadata]
identifier:: /rec/zone-fgjson/mid-points
part:: For DGGRSs not in CRS84, the geometry SHOULD include intermediate points between the vertices of the zone geometry so as to accurately represent the shape of the zones.
====

[recommendation]
====
[%metadata]
identifier:: /rec/zone-fgjson/geometry
part:: The implementation SHOULD support a `geometry` query parameter allowing a client to choose how to return the geometry of each zone.
part:: The implementation SHOULD support a value of `geometry=zone-centroid` to request a representation where the geometry of each a zone is a Point geometry for the centroid of that zone.
part:: The implementation SHOULD support a value of `geometry=zone-region` to request a representation where the geometry of each zone is a (Multi)Polygon or Polyhedron geometry.
part:: The implementation SHOULD support a value of `geometry=none` to request a representation with a null geometry.
part:: If a requested geometry representation is not supported, the Implementation SHOULD return a 4xx or 501 "Not Implemented" HTTP error.
====
