[[rc-table_collection-dggs]]
[requirements_class]
.Requirements Class Collection DGGS
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/collection-dggs
subject:: Web API
inherit:: https://www.opengis.net/spec/ogcapi-common-2/1.0/req/collections
requirement:: /req/collection-dggs/dggs
====

=== Collection DGGS (`/collections/{collectionId}/dggs`)

[requirement]
====
[%metadata]
identifier:: /req/collection-dggs/dggs
description:: For collection DGGS resources:
part:: The Implementation SHALL support the resource paths and associated HTTP methods defined in the "Core" requirements class, as well as any additional resources defined in other requirements classes to which the
Implementation declares conformance, for at least one collection of the dataset offered by the API deployment.
part:: The Implementation SHALL include a link to the list of available DGGRSs for the collection at `/collections/{collectionId}/dggs` in the links of the collection using the link relation type `[ogc-rel:dggrs-list]`.
part:: The `/collections/{collectionId}/dggs` and `/collections/{collectionId}/dggs/{dggrsId}` resources SHALL include a link to the collection using the link relation type `[ogc-rel:geodata]`.
====

See also <<examples_collection_description,Examples C.1>>.
