[[rc_table-zone_geojson]]

[requirements_class]
.Requirements Class GeoJSON Zone List
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/zone-geojson
subject:: Web API
inherit:: <<rfc7946, GeoJSON>>
inherit:: <<OGC21-045r1>> (optional JSON-FG dependency)
inherit:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/zone-query
requirement:: /req/zone-geojson/content
====

[requirement]
====
[%metadata]
identifier:: /req/zone-geojson/content
description:: For returning zone lists encoded as GeoJSON:
part:: Every 200 response of the server for zone query with the media type `application/geo+json` SHALL be a GeoJSON document consisting of a FeatureCollection, where every Feature represents a single zone.
part:: Unless otherwise specified by a prior arrangement (for example, an output `crs` query parameter) or by negotiating a JSON-FG profile, the coordinate reference system SHALL be CRS84(h) in longitude and latitude (and optional height above the WGS84 ellipsoid).
part:: Every feature SHALL have a `zoneID` property corresponding to the textual identifier of the zone.
part:: The geometry of each feature SHALL be the geometry of the zone.
part:: If returning a JSON-FG profile, the profile URI SHALL be included in the `links` section of the JSON-FG response.
====

[recommendation]
====
[%metadata]
identifier:: /rec/zone-geojson/jsonfg-profile
part:: The Implementation SHOULD support a `profile` query parameter for zone query requests allowing to negotiate an https://docs.ogc.org/DRAFTS/21-045r1.html[OGC Feature & Geometry JSON] representation,
where a value of `rfc7946` corresponds to RFC 7936 GeoJSON, a `jsonfg` value corresponds to a response conforming to JSON-FG, and a `jsonfg-plus` value corresponds to a response conforming to JSON-FG
fully backward compatible with GeoJSON (e.g., including a GeoJSON geometry in the `geometry` field if geometry is otherwise provided in the JSON-FG-specific `place` property which supports extended
geometry types and alternate coordinate reference system without prior agreement).
====

[recommendation]
====
[%metadata]
identifier:: /rec/zone-geojson/profile-links
part:: If returning a JSON-FG representation, the implementation SHOULD also return a link to the default or selected profile as a `Link` HTTP response header, for example `Link: https://www.opengis.net/def/profile/ogc/0/jsonfg; rel="profile"`.
====

[permission]
====
[%metadata]
identifier:: /per/zone-geojson/supported-rofiles
part:: An Implementation MAY support only a subset of the defined GeoJSON profiles.
part:: An Implementation MAY return any profile as the default when the `profile` query parameter is not specified in the request.
====

[recommendation]
====
[%metadata]
identifier:: /rec/zone-geojson/id
part:: The Feature `id` SHOULD be a sequential identifier starting at 1, have the same text value as the `zoneID` property, or correspond to the 64-bit integer identifier for the zone.
====

[recommendation]
====
[%metadata]
identifier:: /rec/zone-geojson/crs
part:: For an JSON-FG response for which a `crs` query parameter is not specified, the CRS of the response SHOULD be consistent with the CRS of the DGGRS or the underlying geographic CRS (e.g., CRS84).
part:: For an JSON-FG response for which a `crs` query parameter is specified, the `geometry` property SHOULD be used to return coordinates if the geometry does not require an extended JSON-FG type, since this constitutes a prior arrangement regarding the CRS of GeoJSON coordinates.
====

[recommendation]
====
[%metadata]
identifier:: /rec/zone-geojson/mid-points
part:: For DGGRSs not in CRS84, the geometry SHOULD include intermediate points between the vertices of the zone geometry so as to accurately represent the shape of the zones.
====

[recommendation]
====
[%metadata]
identifier:: /rec/zone-geojson/geometry
part:: The implementation SHOULD support a `geometry` query parameter allowing a client to choose how to return the geometry of each zone.
part:: The implementation SHOULD support a value of `geometry=zone-centroid` to request a representation where the geometry of each a zone is a Point geometry for the centroid of that zone.
part:: The implementation SHOULD support a value of `geometry=zone-region` to request a representation where the geometry of each zone is a (Multi)Polygon, (Multi)Polyhedron, or (Multi)Prism.
part:: The implementation SHOULD support a value of `geometry=none` to request a representation with a null geometry.
part:: If a requested geometry representation is not supported, the Implementation SHOULD return a 4xx HTTP error.
====
