[[rc_table-data_json]]

[requirements_class]
.Requirements Class DGGS-JSON Zone Data
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-json
subject:: Web API
inherit:: <<rfc8259, JSON>>
inherit:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-retrieval
====

[requirement]
====
[%metadata]
identifier:: /req/data-json/content
part:: Every 200 response of the server for zone data with the media type `application/json` SHALL be a JSON document representing the data values for all selected fields of each included sub-zone.
part:: The schema for the JSON document SHALL follow the JSON Schema for DGGS-JSON described below.
part:: Every zone depth requested using the `zone-depth` parameter SHALL be included in the response.
part:: At every depth, each individual value SHALL correspond exactly to the data sampled representative of that sub-zone.
part:: The list of data values SHALL follow the default zone order as specified by the Discrete Global Grid Reference System (for example based on a scanline or space-filling curved defined therein) for which the request is made.
part:: Null values SHALL use the `null` JSON value.
====

.JSON Schema for DGGS-JSON
[source,json]
----
include::../schemas/dggs-json/dggs-json.json[]
----
