[[rc_table-data_geojson]]

[requirements_class]
.Requirements Class GeoJSON
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-geojson
subject:: Web API
inherit:: <<rfc7946, GeoJSON>>
inherit:: <<OGC21-045r1>> (optional FG-JSON dependency)
inherit:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-retrieval
requirement:: /req/data-geojson/content
====

[requirement]
====
[%metadata]
identifier:: /req/data-geojson/content
part:: Every 200 response of the server for zone data with the media type `application/geo+json` SHALL be a https://datatracker.ietf.org/doc/html/rfc7946[GeoJSON] document representing the features, including their geometry and associated properties, for a single zone.
part:: Unless otherwise specified by a prior arrangement (for example, an output `crs` query parameter) or by negotiating an FG-JSON profile, the coordinate reference system SHALL be CRS84(h) in longitude and latitude (and optional height above the WGS84 ellipsoid).
part:: Features whose geometry lie wholly outside of the zone geometry SHALL NOT be included in the response.
====

[recommendation]
====
[%metadata]
identifier:: /req/data-geojson/fgjson-profile
part:: The Implementation SHOULD support a `profile` query parameter for zone data requests allowing to negotiate an https://docs.ogc.org/DRAFTS/21-045r1.html[OGC Feature & Geometry JSON] representation,
where a value of `rfc7946` corresponds to RFC 7936 GeoJSON, a `jsonfg` value corresponds to a response conforming to FG-JSON, and a `jsonfg-plus` value corresponds to a response conforming to FG-JSON
fully backward compatible with GeoJSON (e.g., including a GeoJSON geometry in the `geometry` field if geometry is otherwise provided in the FG-JSON-specific `place` property which supports extended
geometry types and alternate coordinate reference system without prior agreement).
====

[recommendation]
====
[%metadata]
identifier:: /rec/data-geojson/clipping
part:: For features partially inside of the zone geometry, the geometry included in the response SHOULD be clipped to the boundaries of the zone geometry.
====

[recommendation]
====
[%metadata]
identifier:: /rec/data-geojson/generalization
part:: The geometry of the features in the response SHOULD be generalized to the scale associated with the hierarchy level implied from the `zone-depth` relative to the requested zone.
====

[recommendation]
====
[%metadata]
identifier:: /rec/data-geojson/omission
part:: For datasets whose features have either a size (such as areal or linear feature) or other properties making some features irrelevant at lower hierarchy levels, such irrelevant features SHOULD
be omitted from the response based on the hierarchy level implied from the `zone-depth` relative to the requested zone.
====

[recommendation]
====
[%metadata]
identifier:: /rec/data-geojson/crs
part:: For an FG-JSON response for which a `crs` query parameter is not specified, the CRS of the response SHOULD be consistent with the CRS of the DGGRS or the underlying geographic CRS (e.g., CRS84).
part:: For an FG-JSON response for which a `crs` query parameter is specified, the `geometry` property SHOULD be used to return coordinates if the geometry does not require an extended FG-JSON type, since this constitutes a prior arrangement regarding the CRS of GeoJSON coordinates.
====

[recommendation]
====
[%metadata]
identifier:: /rec/data-geojson/geometry
part:: The implementation SHOULD support a `geometry` query parameter allowing a client to choose how to return feature geometry.
part:: The implementation SHOULD support a value of `geometry=zone-centroid` to request a representation where each feature is a zone intersecting the data, with the feature geometry of each feature being a Point geometry for the centroid of that zone.
part:: The implementation SHOULD support a value of `geometry=zone-region` to request a representation where each feature is a zone intersecting the data, with the geometry of each feature being a (Multi)Polygon, (Multi)Polyhedron or (Multi)Prism.
part:: The implementation SHOULD support a value of `geometry=vectorized` to request a representation where each feature corresponds to a feature of the data (sharing identical property values).
part:: If a `geometry` value is not specified, the Implementation SHOULD return the representation closest to the native data.
part:: If a requested geometry representation is not supported, the Implementation SHOULD return a 4xx HTTP error.
====
