[[rc_table-data_geotiff]]

[requirements_class]
.Requirements Class GeoTIFF Data
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-geotiff
subject:: Web API
inherit:: <<TIFF_V6>>
inherit:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-retrieval
====

[requirement]
====
[%metadata]
identifier:: /req/data-geotiff/content
part:: Every 200 response of the server for zone data with the media type image/tiff SHALL be a TIFF document representing the data values for all selected fields for a single zone.
part:: All zone representing parts of the same resource or resources and using the same style SHALL follow the same portrayal rules or represent data with the same reference and units of measure.
part:: If the TIFF encoding incorporates a GeoTIFF georeference, this information SHALL be consistent with the DGGRS Zone ID and the CRS implied by the DGGRS.
part:: If the zone geometry is not rectangular, the closest bounding rectangle SHALL be used for referencing the image, and null values SHALL be used for cells lying outside the zone geometry.
part:: A distinct value for each sub-zone implied from the requested `zone-depth` SHALL correspond to at least one distinct cell value in the response.
part:: For implementations supporint Data Custom Depths, each depth of the requested zone depth pyramid SHALL be a separate image (overview) in the response.
====
