[[rc_table-data_coveragejson]]

[requirements_class]
.Requirements Class CoverageJSON Data
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-coveragejson
subject:: Web API
inherit:: <<OGC21-069r2>>
inherit:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-retrieval
requirement:: /req/data-coveragejson/content
====

==== CoverageJSON Zone Data

[requirement]
====
[%metadata]
identifier:: /req/data-coveragejson/content
description:: For encoding zone data as CoverageJSON
part:: Every 200 response of the server for zone data with the media type `application/prs.coverage+json` SHALL be a https://covjson.org/[CoverageJSON] file representing the data values for all selected fields of each included sub-zone.
part:: For a DGGS-optimized profile (`covjson-dggs`, `covjson-dggs-zoneids`), the profile URI, the global identifier of the parent zone and a URI or link to the DGGRS definition SHALL be included as metadata.
part:: For a DGGS-optimized profile, coordinates along one dimension SHALL correspond to sub-zones, either as global zone identifiers (`covjson-dggs-zoneids`) or
local sub-zone indices following the deterministic DGGRS sub-zone order (`covjson-dggs`), while spatiotemporal dimensions of the DGGRS SHALL NOT be defined as separate dimensions.
part:: For non-DGGS-optimized profiles, if the CoverageJSON encoding incorporates georeferencing information, this information SHALL be consistent with the DGGRS Zone ID.
part:: For non-DGGS-optimized profiles, if the zone geometry is not rectilinear, the closest bounding rectangle (or volume) SHALL be used for referencing the data.
part:: For non-DGGS-optimized profiles, a distinct value for each sub-zone implied from the requested `zone-depth` SHALL correspond to at least one distinct cell value in the response.
====

[recommendation]
====
[%metadata]
identifier:: /rec/data-coveragejson/null-values
part:: For non-DGGS-optimized profiles, null values SHOULD be used for cells lying outside the zone geometry.
====

[recommendation]
====
[%metadata]
identifier:: /rec/data-coveragejson/crs
part:: For non-DGGS-optimized profiles, the CRS of the response SHOULD be consistent with either the DGGRS or the underlying geographic CRS (e.g., CRS84).
====


[recommendation]
====
[%metadata]
identifier:: /rec/data-coveragejson/profile
part:: The Implementation SHOULD support a `profile` query parameter for zone data requests allowing to negotiate a particular representation, including the selection of
a dimension representing global sub-zone identifiers (`covjson-dggs-zoneids`) or local sub-zone indices based on the deterministic order as defined by the DGGRS (`covjson-dggs`),
or individual spatiotemporal dimensions for interoperability with non-DGGS clients (`covjson`).
====

[recommendation]
====
[%metadata]
identifier:: /rec/data-coveragejson/profile-links
part:: The implementation SHOULD return a link to the default or selected profile as a `Link` HTTP response header, for example `Link: https://www.opengis.net/def/profile/ogc/0/covjson-dggs; rel="profile"`.
====

[permission]
====
[%metadata]
identifier:: /per/data-coveragejson/supported-profiles
part:: An Implementation MAY support only a subset of the defined CoverageJSON profiles.
part:: An Implementation MAY return any profile as the default when the `profile` query parameter is not specified in the request. As an example, this allows for static servers to return only a DGGS-optimized CoverageJSON representation.
====
