[[rc_table-data_coveragejson]]

[requirements_class]
.Requirements Class CoverageJSON Data
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-coveragejson
subject:: Web API
inherit:: <<OGC21-069r2>>
inherit:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-retrieval
====

[requirement]
====
[%metadata]
identifier:: /req/data-coveragejson/content
part:: Every 200 response of the server for zone data with the media type `application/prs.coverage+json` SHALL be a https://covjson.org/[CoverageJSON] file representing the data values for all selected fields for a single zone.
part:: If the CoverageJSON encoding incorporates georeferencing information, this information SHALL be consistent with the DGGRS Zone ID.
part:: If the zone geometry is not rectilinear, the closest bounding rectangle (or volume) SHALL be used for referencing the data.
part:: A distinct value for each sub-zone implied from the requested `zone-depth` SHALL correspond to at least one distinct cell value in the response.
====

[recommendation]
====
[%metadata]
identifier:: /rec/data-coveragejson/null-values
part:: Null values SHOULD be used for cells lying outside the zone geometry.
====

[recommendation]
====
[%metadata]
identifier:: /rec/data-coveragejson/crs
part:: The CRS of the response SHOULD be consistent with either the DGGRS or the underlying geographic CRS (e.g., CRS84).
====
