[[rc_table-data_fgjson]]

[requirements_class]
.Requirements Class FG-JSON Data
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-fgjson
subject:: Web API
inherit:: <<FG-JSON>>
inherit:: https://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/data-retrieval
====

[requirement]
====
[%metadata]
identifier:: /req/data-fgjson/content
part:: Every 200 response of the server for zone data with the media type `application/fg+json` SHALL be a https://docs.ogc.org/DRAFTS/21-045r1.html[Feature & Geometries JSON] document representing the features, including their geometry and associated properties, for a single zone.
part:: Features whose geometry lie wholly outside of the zone geometry SHALL not be included in the response.
====

[recommendation]
====
[%metadata]
identifier:: /rec/data-fgjson/clipping
part:: For features partially inside of the zone geometry, the geometry included in the response SHOULD be clipped to the boundaries of the zone geometry.
====

[recommendation]
====
[%metadata]
identifier:: /rec/data-fgjson/generalization
part:: The geometry of the features in the response SHOULD be generalized to the scale associated with the hierarchy level implied from the `zone-depth` relative to the requested zone.
====

[recommendation]
====
[%metadata]
identifier:: /rec/data-fgjson/omission
part:: For datasets whose features have either a size (such as areal or linear feature) or other properties making some features irrelevant at lower hierarchy levels, such irrelevant features SHOULD
be omitted from the response based on the hierarchy level implied from the `zone-depth` relative to the requested zone.
====

[recommendation]
====
[%metadata]
identifier:: /rec/data-fgjson/crs
part:: The CRS of the response SHOULD be consistent with either the DGGRS or the underlying geographic CRS (e.g., CRS84).
====
